import {createHash,randomUUID} from 'node:crypto';
import {deflateSync} from 'node:zlib';
import {mkdir,mkdtemp,readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {FileStore} from '../../src/services/video/storage/file-store';
import {LocalAssetBytes} from '../../src/services/video/assets/local-bytes';
import {prepareSourceImage,sourceImageProducerSha} from '../../src/services/video/assets/image-preparation';
import {runOwnedDocker} from '../../src/services/video/media/owned-docker';
import {canonicalHash} from '../../src/services/video/domain/hash';
import {claimProbeReport,persistProbeReport} from './helpers/probe-report';
function crc(data:Buffer){let c=0xffffffff;for(const b of data){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function png(alpha=false){const width=3000,height=1000,header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=alpha?6:2;const channels=alpha?4:3,scan=Buffer.alloc(height*(1+width*channels));for(let y=0;y<height;y++)for(let x=0;x<width;x++){const offset=y*(1+width*channels)+1+x*channels;scan[offset+(x<width/2?0:1)]=255;if(alpha)scan[offset+3]=x<width/2?128:255;}function chunk(kind:string,data:Buffer){const name=Buffer.from(kind),out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);name.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([name,data])),data.length+8);return out}return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(scan)),chunk('IEND',Buffer.alloc(0))])}
function rotatedJpeg(data:Buffer){const exif=Buffer.alloc(32);exif.write('Exif\0\0',0,'ascii');exif.write('II',6);exif.writeUInt16LE(42,8);exif.writeUInt32LE(8,10);exif.writeUInt16LE(1,14);exif.writeUInt16LE(0x112,16);exif.writeUInt16LE(3,18);exif.writeUInt32LE(1,20);exif.writeUInt16LE(6,24);const marker=Buffer.from([255,225,0,34]);return Buffer.concat([data.subarray(0,2),marker,exif,data.subarray(2)])}
async function snapshot(root:string){const out:Record<string,string>={};async function walk(dir:string){for(const e of await readdir(dir,{withFileTypes:true})){const path=join(dir,e.name);if(e.isDirectory())await walk(path);else if(e.name.endsWith('.json'))out[path]=createHash('sha256').update(await readFile(path)).digest('hex')}}await walk(root);return canonicalHash(out)}
async function main(){
 if(process.argv.slice(2).join(' ')!=='--verify-source-images')throw Error('EXPLICIT_DIAGNOSTIC_REQUIRED');
 const build=JSON.parse(await readFile('.video-local/source-image-build-current.json','utf8')),image=(await readFile(join(build.root,'image-id.txt'),'utf8')).trim();if(!/^sha256:[a-f0-9]{64}$/.test(image)||build.producerSha256!==await sourceImageProducerSha())throw Error('PINNED_IMAGE_REQUIRED');
 const legacy=JSON.parse(await readFile('docs/engineering/evidence/clear-full-film-technical-probe.json','utf8')),critic=JSON.parse(await readFile('docs/engineering/evidence/clear-full-film-critic-probe.json','utf8')),unknown=JSON.parse(await readFile('docs/engineering/evidence/runtime-image-decode-after-fix.json','utf8')),originalRoots=[legacy.sourceRoot,critic.root,unknown.root],before=await Promise.all(originalRoots.map(snapshot));
 const root=await mkdtemp(resolve('.video-local/source-image-probe-')),projectId=randomUUID(),operationId=randomUUID(),store=new FileStore(root),journal={store,prefix:`projects/${projectId}/operations/${operationId}/media-effects`},assets=new LocalAssetBytes(root),fixture=join(root,'fixture');await mkdir(fixture,{mode:0o700});
 const path='docs/engineering/evidence/source-image-v3-probe.json',report:Record<string,unknown>&{views:unknown[]}={executedAt:new Date().toISOString(),status:'running',root,image,build,projectId,operationId,modelCalls:0,formalProductionApproval:false,deliveryEligible:false,resultPublished:false,fixture:'Synthetic two-color 3000x1000 image; format/decode/resize/orientation tests only, no semantic QA.',views:[]};await claimProbeReport(path,report);
 const save=()=>persistProbeReport(path,report),assertActive=async()=>{if(canonicalHash(await Promise.all(originalRoots.map(snapshot)))!==canonicalHash(before))throw Error('ORIGINAL_STATE_CHANGED')},env={VIDEO_SOURCE_IMAGE_REF:image,VIDEO_SOURCE_IMAGE_RUNTIME_DIGEST:image.slice(7)};
 try{
  const source=png();await writeFile(join(fixture,'source.png'),source);
  for(const [filename,args] of [['source.jpg',['-q:v','2']],['source.webp',['-c:v','libwebp','-lossless','1']]] as const)await runOwnedDocker(['run','--rm','--network','none','--read-only','--cap-drop','ALL','--security-opt','no-new-privileges','--cpus','2','--memory','512m','--user',`${process.getuid?.()??10001}:${process.getgid?.()??10001}`,'--mount',`type=bind,src=${fixture},dst=/fixture`,image,'ffmpeg','-v','error','-threads','2','-filter_threads','2','-i','/fixture/source.png','-frames:v','1',...args,'/fixture/'+filename],30000,image,assertActive,journal);
  const jpeg=await readFile(join(fixture,'source.jpg')),webp=await readFile(join(fixture,'source.webp'));
  for(const [kind,mime,data,rotated] of [['png','image/png',source,false],['jpeg','image/jpeg',jpeg,false],['webp','image/webp',webp,false],['jpeg-exif6','image/jpeg',rotatedJpeg(jpeg),true],['png-alpha','image/png',png(true),false]] as const){
   const assetId=randomUUID(),uploaded=await assets.put(projectId,assetId,new Request('http://fixture/upload',{method:'PUT',body:data}),{declaredMime:mime,declaredBytes:data.length}),input={projectId,assetId,sourceMime:mime,sourceSha256:uploaded.sha256,sourceBytes:uploaded.bytes};
   const view=await prepareSourceImage(root,input,{env,journal,assertActive});if(view.receipt.width!==(rotated?683:2048)||view.receipt.height!==(rotated?2048:683))throw Error('WRONG_FULL_IMAGE_GEOMETRY');const pixels=[];
   for(const [index,x,y] of [[0,rotated?340:500,rotated?500:340],[1,rotated?340:1500,rotated?1500:340]]){const filename=kind+'-'+index+'.rgb';await runOwnedDocker(['run','--rm','--network','none','--read-only','--cap-drop','ALL','--security-opt','no-new-privileges','--user',`${process.getuid?.()??10001}:${process.getgid?.()??10001}`,'--mount',`type=bind,src=${view.path},dst=/input/view.png,readonly`,'--mount',`type=bind,src=${fixture},dst=/output`,image,'ffmpeg','-v','error','-threads','2','-filter_threads','2','-i','/input/view.png','-frames:v','1','-vf',`crop=2:2:${x}:${y}`,'-pix_fmt','rgba','-f','rawvideo','/output/'+filename],30000,image,assertActive,journal);const pixel=await readFile(join(fixture,filename));if(pixel.length!==16)throw Error('PIXEL_PROOF_MISSING');pixels.push([...pixel.subarray(0,4)])}
   if(pixels[0][0]<200||pixels[0][1]>60||pixels[1][1]<200||pixels[1][0]>60)throw Error('IMAGE_COLORS_OR_ORIENTATION_CHANGED');if(pixels[0][3]!== (kind==='png-alpha'?128:255)||pixels[1][3]!==255)throw Error('IMAGE_TRANSPARENCY_CHANGED');
   const first=await store.listKeys(journal.prefix,1),cold=await prepareSourceImage(root,input,{env,journal,assertActive});if(cold.receipt.sha256!==view.receipt.sha256||canonicalHash(first)!==canonicalHash(await store.listKeys(journal.prefix,1)))throw Error('COLD_REPLAY_CHANGED');
   const original=await readFile(assets.path(projectId,assetId)),viewBytes=await readFile(view.path);let sourceTamperRejected=false,viewTamperRejected=false;
   await writeFile(assets.path(projectId,assetId),Buffer.from('changed'));try{await prepareSourceImage(root,input,{env,journal,assertActive})}catch(error){sourceTamperRejected=(error as Error).message==='RUNTIME_ASSET_CHANGED'}finally{await writeFile(assets.path(projectId,assetId),original)}
   await writeFile(view.path,Buffer.from('changed'));try{await prepareSourceImage(root,input,{env,journal,assertActive})}catch(error){viewTamperRejected=(error as Error).message==='SOURCE_IMAGE_CHANGED'}finally{await writeFile(view.path,viewBytes)}
   if(!sourceTamperRejected||!viewTamperRejected||canonicalHash(first)!==canonicalHash(await store.listKeys(journal.prefix,1)))throw Error('TAMPER_NOT_BLOCKED_WITHOUT_NEW_PRODUCER');report.views.push({kind,input,job:view.job,receipt:view.receipt,path:view.path,pixels,coldNoNewNativeInvocation:true,sourceTamperRejected,viewTamperRejected});await save();
  }
  const broken=Buffer.alloc(24);Buffer.from('89504e470d0a1a0a','hex').copy(broken);broken.write('IHDR',12);const assetId=randomUUID(),uploaded=await assets.put(projectId,assetId,new Request('http://fixture/upload',{method:'PUT',body:broken}),{declaredMime:'image/png',declaredBytes:24});let errorCode='';try{await prepareSourceImage(root,{projectId,assetId,sourceMime:'image/png',sourceSha256:uploaded.sha256,sourceBytes:24},{env,journal,assertActive})}catch(error){errorCode=(error as Error).message}
  if(errorCode!=='IMAGE_DECODE_FAILED')throw Error('BROKEN_IMAGE_NOT_REJECTED');report.brokenImageErrorCode=errorCode;
  const huge=Buffer.from(source);huge.writeUInt32BE(10000,16);huge.writeUInt32BE(4000,20);huge.writeUInt32BE(crc(huge.subarray(12,29)),29);const hugeId=randomUUID(),hugeUpload=await assets.put(projectId,hugeId,new Request('http://fixture/upload',{method:'PUT',body:huge}),{declaredMime:'image/png',declaredBytes:huge.length});let hugeError='';try{await prepareSourceImage(root,{projectId,assetId:hugeId,sourceMime:'image/png',sourceSha256:hugeUpload.sha256,sourceBytes:hugeUpload.bytes},{env,journal,assertActive})}catch(error){hugeError=(error as Error).message}if(hugeError!=='IMAGE_PIXEL_LIMIT')throw Error('PIXEL_LIMIT_NOT_ENFORCED');report.pixelLimitErrorCode=hugeError;report.status='actual_png_jpeg_webp_exif_decode_resize_and_cold_integrity_passed';
 }catch(error){report.status='failed';report.errorCode=(error as Error).message.slice(0,300);process.exitCode=1}
 finally{report.originalProjectModelAndNativeUnknownUnchanged=canonicalHash(await Promise.all(originalRoots.map(snapshot)))===canonicalHash(before);if(!report.originalProjectModelAndNativeUnknownUnchanged){report.status='failed';process.exitCode=1}const keys=await store.listKeys(journal.prefix,1);report.nativeJournal=await Promise.all(keys.map(async key=>(await store.readFresh(key)).value));await save();console.log(JSON.stringify({status:report.status,errorCode:report.errorCode,views:report.views.length,originalUnchanged:report.originalProjectModelAndNativeUnknownUnchanged}))}
}
main().catch(error=>{console.error(String(error.message).slice(0,300));process.exitCode=1});
