import type {MediaJob,MediaJobHandle,MediaStatus} from '../../src/services/video/media/executor';
import {createHash,randomUUID} from 'node:crypto';
import {deflateSync} from 'node:zlib';
import {mkdir,mkdtemp,readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {DockerExecutor,computeStageKey} from '../../src/services/video/media/docker-executor';
import {LocalAssetBytes} from '../../src/services/video/assets/local-bytes';
import {FileStore} from '../../src/services/video/storage/file-store';
import {runOwnedDocker} from '../../src/services/video/media/owned-docker';
import {technicalVideoQa} from '../../src/services/video/media/technical-qa';
import {canonicalHash} from '../../src/services/video/domain/hash';
import {runtimeAssetRendererHashes} from '../../src/services/video/media/runtime-asset-image';
import {claimProbeReport,persistProbeReport} from './helpers/probe-report';
import {observeProbePicture} from './helpers/probe-picture';
function crc(bytes:Buffer){let c=0xffffffff;for(const b of bytes){c^=b;for(let bit=0;bit<8;bit++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function png(){function chunk(type:string,data:Buffer){const name=Buffer.from(type),out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);name.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([name,data])),8+data.length);return out}const header=Buffer.alloc(13);header.writeUInt32BE(16);header.writeUInt32BE(16,4);header[8]=8;header[9]=2;const scan=Buffer.alloc(16*(1+16*3));for(let y=0;y<16;y++)for(let x=0;x<16;x++)scan[y*49+1+x*3+(x<8?0:1)]=255;return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(scan)),chunk('IEND',Buffer.alloc(0))])}
async function snapshot(root:string){const out:Record<string,string>={};async function walk(dir:string){for(const entry of await readdir(dir,{withFileTypes:true})){const path=join(dir,entry.name);if(entry.isDirectory())await walk(path);else if(entry.name.endsWith('.json'))out[path]=createHash('sha256').update(await readFile(path)).digest('hex')}}await walk(root);return canonicalHash(out)}
async function main(){
 if(process.argv.slice(2).join(' ')!=='--verify-private-images')throw Error('EXPLICIT_DIAGNOSTIC_REQUIRED');
 const build=JSON.parse(await readFile('.video-local/runtime-assets-build-current.json','utf8')),image=(await readFile(join(build.root,'image-id.txt'),'utf8')).trim();if(!/^sha256:[a-f0-9]{64}$/.test(image))throw Error('PINNED_IMAGE_REQUIRED');
 const hashes=await runtimeAssetRendererHashes();for(const [file,hash] of Object.entries(hashes))if(build.files[file].sha256!==hash)throw Error('BUILD_SOURCE_CHANGED');
 const legacy=JSON.parse(await readFile('docs/engineering/evidence/clear-full-film-technical-probe.json','utf8')),critic=JSON.parse(await readFile('docs/engineering/evidence/clear-full-film-critic-probe.json','utf8')),originalRoots=[legacy.sourceRoot,critic.root],before=await Promise.all(originalRoots.map(snapshot));
 const root=await mkdtemp(resolve('.video-local/runtime-assets-probe-')),projectId=randomUUID(),operationId=randomUUID(),journal={store:new FileStore(root),prefix:`projects/${projectId}/operations/${operationId}/media-effects`},id=randomUUID(),data=png(),upload=await new LocalAssetBytes(root).put(projectId,id,new Request('http://fixture/upload',{method:'PUT',body:data}),{declaredMime:'image/png',declaredBytes:data.length}),asset={id,mime:'image/png' as const,bytes:upload.bytes,sha256:upload.sha256};
 const path='docs/engineering/evidence/runtime-assets-v4-probe.json',report:Record<string,unknown>&{stages:Array<{kind:string;job:MediaJob;handle:MediaJobHandle;status?:MediaStatus}>}={executedAt:new Date().toISOString(),status:'running',root,image,build,projectId,operationId,modelCalls:0,formalProductionApproval:false,resultPublished:false,deliveryEligible:false,fixture:'Synthetic two-color PNG used only to test actual private-image transport; no user semantic/style QA claimed.',asset,stages:[]};await claimProbeReport(path,report);
 const save=()=>persistProbeReport(path,report),assertActive=async()=>{if(canonicalHash(await Promise.all(originalRoots.map(snapshot)))!==canonicalHash(before))throw Error('ORIGINAL_STATE_CHANGED')},env={VIDEO_MEDIA_IMAGE_REF:image,VIDEO_MEDIA_RUNTIME_DIGEST:image.slice(7),VIDEO_MEDIA_TIMEOUT_SECONDS:'120'},executor=new DockerExecutor(root,env,{assertActive,journal});
 function job(url:string,attemptId:string,runtimeDigest=image.slice(7)){const sourceHtml=`<!doctype html><html><style>html,body{margin:0}canvas{display:block}</style><canvas width="320" height="180"></canvas><script>const img=new Image();img.onload=()=>window.READY=true;img.onerror=()=>window.READY=true;img.src=${JSON.stringify(url)};window.render=t=>{if(!img.naturalWidth)throw Error('REQUIRED_IMAGE_MISSING');const ctx=document.querySelector('canvas').getContext('2d');ctx.reset();ctx.drawImage(img,0,0,320,180)};</script></html>`,parameters={projectId,bundleHash:canonicalHash({fixture:asset,url}),runtimeDigest,sourceHtml,logicalWidth:320,logicalHeight:180,outputWidth:320,outputHeight:180,fps:24 as const,startFrame:0,endFrame:24,seed:1,fence:0,assets:[asset]};return{...parameters,operationId,attemptId,stageKey:computeStageKey(parameters)}}
 try{
  // Immutable OLD image accepts a foreign image that the job never declared.
  const old=job('/assets/foreign.bin','legacy-undeclared',build.baseImage.slice(7));old.assets=[];old.stageKey=computeStageKey(old);const oldDir=join(root,'media',old.stageKey);await mkdir(join(oldDir,'assets'),{recursive:true});await writeFile(join(oldDir,'assets','foreign.bin'),data);await writeFile(join(oldDir,'scene.html'),old.sourceHtml);await writeFile(join(oldDir,'job.json'),JSON.stringify(old));const args=['run','--rm','--network','none','--read-only','--cap-drop','ALL','--security-opt','no-new-privileges','--pids-limit','128','--cpus','4','--memory','8g','--user',`${process.getuid?.()??10001}:${process.getgid?.()??10001}`,'--tmpfs','/tmp:rw,nosuid,size=256m','--mount',`type=bind,src=${oldDir},dst=/work/${old.stageKey}`,'--mount',`type=bind,src=${oldDir}/job.json,dst=/work/${old.stageKey}/job.json,readonly`,'--mount',`type=bind,src=${oldDir}/scene.html,dst=/work/${old.stageKey}/scene.html,readonly`,build.baseImage,'node','/opt/videobuddy/render.mjs',`/work/${old.stageKey}/job.json`];await runOwnedDocker(args,150000,build.baseImage,assertActive,journal);report.legacyUndeclaredImageAccepted=true;await save();
  const positive=job('/assets/'+id+'.bin','authorized-image'),result=await observeProbePicture(executor,positive,async handle=>{report.stages.push({kind:'authorized',job:positive,handle});await save()},assertActive,150000);report.stages[0].status=await executor.inspect(result);const dir=join(root,'media',positive.stageKey);report.technicalQa=await technicalVideoQa(dir,image,'output/picture.mp4',{width:320,height:180,durationSec:1,fps:24,audio:false});await save();
  const pixels=[];for(const x of [80,240]){const filename='pixel-'+x+'.rgb';await runOwnedDocker(['run','--rm','--network','none','--read-only','--cap-drop','ALL','--security-opt','no-new-privileges','--user',`${process.getuid?.()??10001}:${process.getgid?.()??10001}`,'--mount',`type=bind,src=${dir},dst=/input,readonly`,'--mount',`type=bind,src=${dir}/output,dst=/output`,image,'ffmpeg','-v','error','-threads','2','-filter_threads','2','-i','/input/output/picture.mp4','-frames:v','1','-vf',`crop=2:2:${x}:90`,'-pix_fmt','rgb24','-f','rawvideo','/output/'+filename],30000,image,assertActive,journal);const pixel=await readFile(join(dir,'output',filename));if(pixel.length!==12)throw Error('PIXEL_PROOF_MISSING');pixels.push([...pixel.subarray(0,3)])}if(pixels[0][0]<150||pixels[0][1]>80||pixels[1][1]<150||pixels[1][0]>80)throw Error('IMAGE_NOT_PRESENT');report.decodedPixels=pixels;await save();
  const negative=job('/assets/foreign.bin','undeclared-image'),negativeDir=join(root,'media',negative.stageKey);await mkdir(join(negativeDir,'assets'),{recursive:true});await writeFile(join(negativeDir,'assets','foreign.bin'),data);const handle=await observeProbePicture(executor,negative,async handle=>{report.stages.push({kind:'undeclared',job:negative,handle});await save()},assertActive,150000,'failed');report.stages[1].status={status:'failed',outputs:[]};report.undeclaredImageRejected=true;const stopped=await executor.cancel(handle);if(stopped.status!=='cancelled')throw Error('MEDIA_STOP_UNKNOWN');await assertActive();
  const corruptId=randomUUID(),corruptData=Buffer.alloc(24);Buffer.from('89504e470d0a1a0a','hex').copy(corruptData);corruptData.write('IHDR',12);const corruptUpload=await new LocalAssetBytes(root).put(projectId,corruptId,new Request('http://fixture/upload',{method:'PUT',body:corruptData}),{declaredMime:'image/png',declaredBytes:24});
  const corrupt={...job('/assets/'+corruptId+'.bin','corrupt-decode'),assets:[{id:corruptId,mime:'image/png' as const,bytes:24,sha256:corruptUpload.sha256}],sourceHtml:"<!doctype html><script>window.Image=class{decode(){return Promise.resolve()}};HTMLImageElement.prototype.decode=()=>Promise.resolve();window.READY=true;window.render=t=>{};</script>"};corrupt.stageKey=computeStageKey(corrupt);
  const corruptHandle=await observeProbePicture(executor,corrupt,async handle=>{report.stages.push({kind:'corrupt-decoder-override',job:corrupt,handle});await save()},assertActive,150000,'failed');report.stages[2].status={status:'failed',outputs:[]};const corruptStopped=await executor.cancel(corruptHandle);if(corruptStopped.status!=='cancelled')throw Error('MEDIA_STOP_UNKNOWN');report.corruptImageWithDecoderOverrideRejected=true;await assertActive();report.status='actual_private_image_rendered_and_undeclared_resource_blocked';
 }catch(error){report.status='failed';report.errorCode=(error as Error).message.slice(0,300);process.exitCode=1}
 finally{report.originalStateNativeAndModelUnknownUnchanged=canonicalHash(await Promise.all(originalRoots.map(snapshot)))===canonicalHash(before);if(!report.originalStateNativeAndModelUnknownUnchanged){report.status='failed';process.exitCode=1}const keys=await journal.store.listKeys(journal.prefix,1);report.nativeJournal=await Promise.all(keys.map(async key=>(await journal.store.readFresh(key)).value));await save();console.log(JSON.stringify({status:report.status,error:report.errorCode,technical:report.technicalQa,decodedPixels:report.decodedPixels,originalUnchanged:report.originalStateNativeAndModelUnknownUnchanged}))}
}
main().catch(error=>{console.error(String(error.message).slice(0,300));process.exitCode=1});
