import {readFile,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {FileStore} from '../../src/services/video/storage/file-store';
import {readSourceImageView} from '../../src/services/video/assets/image-preparation';
import {guardSourceImageProof} from '../../src/contracts/video/source-image';
import {guardImageModelView} from '../../src/contracts/video/image-understanding';
import {canonicalHash} from '../../src/services/video/domain/hash';
import {claimProbeReport,persistProbeReport} from './helpers/probe-report';
async function snapshot(root:string){const files:Record<string,string>={};async function walk(dir:string){for(const item of await readdir(dir,{withFileTypes:true})){const path=join(dir,item.name);if(item.isDirectory())await walk(path);else if(item.name.endsWith('.json'))files[path]=createHash('sha256').update(await readFile(path)).digest('hex')}}await walk(root);return canonicalHash(files)}
async function main(){
 if(process.argv.slice(2).join(' ')!=='--verify-readonly-image-views')throw Error('EXPLICIT_DIAGNOSTIC_REQUIRED');
 const source=JSON.parse(await readFile('docs/engineering/evidence/source-image-v3-probe.json','utf8')),legacy=JSON.parse(await readFile('docs/engineering/evidence/clear-full-film-technical-probe.json','utf8')),critic=JSON.parse(await readFile('docs/engineering/evidence/clear-full-film-critic-probe.json','utf8')),unknown=JSON.parse(await readFile('docs/engineering/evidence/runtime-image-decode-after-fix.json','utf8'));
 if(source.status!=='actual_png_jpeg_webp_exif_decode_resize_and_cold_integrity_passed')throw Error('SOURCE_PROBE_NOT_PASSED');
 const roots=[source.root,legacy.sourceRoot,critic.root,unknown.root],before=await Promise.all(roots.map(snapshot)),store=new FileStore(source.root),path='docs/engineering/evidence/image-view-recovery-v2-probe.json',report:Record<string,unknown>&{views:unknown[]}={executedAt:new Date().toISOString(),status:'running',sourceReport:'source-image-v3-probe.json',root:source.root,modelCalls:0,nativeInvocations:0,originalStateWrites:0,formalProductionApproval:false,deliveryEligible:false,resultPublished:false,views:[]};await claimProbeReport(path,report);
 const assertActive=async()=>{if(canonicalHash(before)!==canonicalHash(await Promise.all(roots.map(snapshot))))throw Error('ORIGINAL_STATE_CHANGED')};
 try{for(const view of source.views){const invocation=source.nativeJournal.find((record:{output?:string})=>record.output&&JSON.parse(record.output).jobSha256===view.job.jobSha256);if(!invocation||invocation.state!=='completed')throw Error('SOURCE_NATIVE_RECEIPT_MISSING');const proof=guardSourceImageProof({schemaVersion:1,operationId:source.operationId,argumentsSha256:invocation.argsSha256,job:view.job,receipt:view.receipt},view.input),journal={store,prefix:`projects/${source.projectId}/operations/${source.operationId}/media-effects`},actual=await readSourceImageView(source.root,view.input,proof,{journal,assertActive}),input={assetId:view.input.assetId,mime:view.input.sourceMime,sha256:view.input.sourceSha256,bytes:view.input.sourceBytes,intendedUse:'本地格式诊断资料'};guardImageModelView(input,proof,actual.data);report.views.push({kind:view.kind,proofSha256:canonicalHash(proof),sourceSha256:input.sha256,viewSha256:actual.receipt.sha256,bytes:actual.data.length,width:actual.receipt.width,height:actual.receipt.height,coordinates:actual.receipt.coordinates,nativeState:'completed',actualOriginalAndViewVerified:true})}await assertActive();report.status='five_actual_source_views_readonly_recovery_passed'}catch(error){report.status='failed';report.errorCode=(error as Error).message.slice(0,300);process.exitCode=1}finally{report.originalProjectAndBothUnknownAndSourceJournalUnchanged=canonicalHash(before)===canonicalHash(await Promise.all(roots.map(snapshot)));if(!report.originalProjectAndBothUnknownAndSourceJournalUnchanged){report.status='failed';process.exitCode=1}await persistProbeReport(path,report);console.log(JSON.stringify({status:report.status,views:report.views.length,originalUnchanged:report.originalProjectAndBothUnknownAndSourceJournalUnchanged}))}
}
main().catch(error=>{console.error(String(error.message).slice(0,300));process.exitCode=1});
