import {createHash} from 'node:crypto';
import {readFile,mkdtemp} from 'node:fs/promises';
import {resolve} from 'node:path';
import type {Environment} from '../../src/services/video/config/environment';
import {FileStore} from '../../src/services/video/storage/file-store';
import {ProjectStore} from '../../src/services/video/storage/project-store';
import {canonicalHash} from '../../src/services/video/domain/hash';
import {readPublishedPreview} from '../../src/services/video/preview/commit';
import {readNarrationJson} from '../../src/services/video/audio/narration-package';
import {loadVerifiedFilmPackage} from '../../src/contracts/video/film-package';
import {contentReviewContext} from '../../src/contracts/video/content-review';
import {readVisualEvidence,type VisualEvidence} from '../../src/services/video/quality/visual-evidence';
import {verifyPostMixNarration} from '../../src/services/video/audio/postmix-asr';
import {validateNarrationPolicySource} from '../../src/services/video/audio/narration-policy';
import {resolvePreviewPostMixReview} from '../../src/services/video/preview/postmix-review';
import {claimProbeReport,persistProbeReport} from './helpers/probe-report';
async function main(){
 if(process.argv.slice(2).join(' ')!=='--prepare-clear-content-context')throw Error('CONTENT_CONTEXT_FLAG_REQUIRED');
 const source=JSON.parse(await readFile('docs/engineering/evidence/clear-full-film-technical-probe.json','utf8')),published=JSON.parse(await readFile('docs/engineering/evidence/clear-frozen-preview-continuation-probe.json','utf8'));
 if(source.status!=='actual_clear_1080p_composition_postmix_and_two_round_frames_verified')throw Error('CONTENT_CONTEXT_SOURCE_REQUIRED');
 const store=new FileStore(source.sourceRoot),projects=new ProjectStore(store),prefix=`projects/${source.projectId}/`,journal={store,prefix:prefix+`operations/${source.journalOperationId}/media-effects`},keys=[prefix+'control',prefix+'budget',prefix+'operations/'+published.operation.id,prefix+'operations/'+published.sourceOperationId],before=await Promise.all(keys.map(async key=>canonicalHash((await store.readFresh(key)).value))),nativeBefore=canonicalHash(await Promise.all((await store.listKeys(journal.prefix,1)).map(async key=>(await store.readFresh(key)).value))),path='docs/engineering/evidence/clear-content-context-v2-probe.json',report:Record<string,unknown>={executedAt:new Date().toISOString(),status:'started',sourceRoot:source.sourceRoot,technicalRoot:source.root,sourceProjectId:source.projectId,newModelCalls:0,predecessorReportSha256:canonicalHash(JSON.parse(await readFile('docs/engineering/evidence/clear-content-context-probe.json','utf8'))),requirementsPolicy:'unclassified_frozen_facts_default_literal',formalProductionApproval:false,resultPublished:false,deliveryEligible:false};
 await claimProbeReport(path,report);let networkCalls=0;globalThis.fetch=async()=>{networkCalls++;throw Error('CONTENT_CONTEXT_NETWORK_FORBIDDEN')};
 async function assertActive(){await projects.access('new-theme-validation',source.projectId);if(canonicalHash(before)!==canonicalHash(await Promise.all(keys.map(async key=>canonicalHash((await store.readFresh(key)).value)))))throw Error('CONTENT_CONTEXT_SOURCE_CHANGED')}
 try{
  await assertActive();const bundle=await readPublishedPreview(projects,source.projectId,published.operation.id,published.operation.consentEpoch,published.operation.previewId,source.sourceRoot);
  if(canonicalHash(bundle)!==canonicalHash(source.bundle))throw Error('CONTENT_CONTEXT_SOURCE_CHANGED');
  const revisionPrefix=prefix+`revisions/${bundle.revisionId}/`,frozen=await loadVerifiedFilmPackage(store,await readNarrationJson(store,bundle.filmSpecRef,revisionPrefix+'film/'),source.sourceRoot),voice=(await store.readFresh<{planRef:typeof bundle.filmSpecRef;verifiedRef:typeof bundle.filmSpecRef}>(revisionPrefix+'voice-stage')).value,{plan,verified}=await validateNarrationPolicySource(projects,source.sourceRoot,source.projectId,bundle.revisionId,voice.planRef,voice.verifiedRef),env:Environment={VIDEO_MEDIA_IMAGE_REF:'sha256:'+frozen.filmSpec.runtimeDigest,VIDEO_MEDIA_RUNTIME_DIGEST:frozen.filmSpec.runtimeDigest,VIDEO_MEDIA_TIMEOUT_SECONDS:'600',VIDEO_ASR_IMAGE_REF:'sha256:caa3fca3e3e6866dab7351346367768db612bb411f06fbd4a7a44f767747f5d4',VIDEO_ASR_RUNTIME_DIGEST:'caa3fca3e3e6866dab7351346367768db612bb411f06fbd4a7a44f767747f5d4',VIDEO_ASR_MODEL:'Systran/faster-whisper-medium'},movie=source.movie;
  const bytes=await readFile(movie.outputPath);if(bytes.length!==movie.technicalQa.bytes||createHash('sha256').update(bytes).digest('hex')!==movie.technicalQa.sha256)throw Error('CONTENT_CONTEXT_FILM_CHANGED');
  const postmix=await verifyPostMixNarration(source.sourceRoot,{outputPath:movie.outputPath,sha256:movie.technicalQa.sha256,durationMs:frozen.filmSpec.output.totalFrames*1000/frozen.filmSpec.output.fps,technicalQa:'pass'},plan,verified,env,undefined,{downmix:'stereo_average',journal,mustExist:true,assertActive,resolveReview:context=>resolvePreviewPostMixReview(projects,source.sourceRoot,source.projectId,bundle.revisionId,context,{mustExist:true,verified})});
  if(postmix.status!=='pass'||canonicalHash(postmix)!==canonicalHash(source.postmix))throw Error('CONTENT_CONTEXT_POSTMIX_CHANGED');
  const selected=new Set<number>(frozen.timeline.captions.map(c=>c.stableReadableStartFrame)),frames=[];
  const batches:Array<{round:1|2;index:number;evidence:VisualEvidence}>=source.visualBatches;
  for(const batch of batches.filter(b=>b.round===1)){if(batch.evidence.filmSha256!==movie.technicalQa.sha256||batch.evidence.runtimeDigest!==frozen.filmSpec.runtimeDigest)throw Error('CONTENT_CONTEXT_FRAME_CHANGED');if(batch.evidence.frames.some(f=>selected.has(f.frame))){await readVisualEvidence(source.root,batch.evidence);for(const {id,frame,sha256,bytes} of batch.evidence.frames)if(selected.has(frame))frames.push({id,frame,sha256,bytes})}}
  if(frames.length!==selected.size)throw Error('CONTENT_CONTEXT_FRAME_CHANGED');frames.sort((a,b)=>a.frame-b.frame);
  const transcripts=postmix.lines.map(line=>{const clock=frozen.timeline.narration.find(n=>n.lineId===line.lineId);if(!clock)throw Error('CONTENT_CONTEXT_POSTMIX_CHANGED');return{id:line.lineId,startSample:clock.startSample,endSample:clock.endSample,audioSha256:line.sourceSha256,text:line.recognizedText,verification:line.status}}),context=contentReviewContext({filmSha256:movie.technicalQa.sha256,filmSpecSha256:bundle.filmSpecRef.sha256,factsManifestSha256:frozen.filmSpec.factsRef.sha256,fps:frozen.timeline.fps,totalFrames:frozen.timeline.totalFrames,facts:frozen.facts.facts,frames,transcripts}),root=await mkdtemp(resolve('.video-local/clear-content-context-')),isolated=new ProjectStore(new FileStore(root)),contextRef=await isolated.index.immutable('content-review/context',context),cold=await readNarrationJson(new FileStore(root),contextRef,'content-review/context/');
  if(canonicalHash(context)!==canonicalHash(cold))throw Error('CONTENT_CONTEXT_COLD_CHANGED');await assertActive();
  Object.assign(report,{status:'actual_frozen_content_context_verified_no_judgment',root,filmSpecRef:bundle.filmSpecRef,factsRef:frozen.filmSpec.factsRef,contextRef,context,coldIdentical:true,rawTranscriptsPreserved:true,selectedFrames:frames.length,completeFrozenFacts:frozen.facts.facts.length,asrVerificationStatuses:postmix.lines.map(l=>l.status)});
 }catch(error){report.status='failed';report.errorCode=(error as Error).message;process.exitCode=1}
 finally{report.networkCalls=networkCalls;report.nativeInvocationsUnchanged=nativeBefore===canonicalHash(await Promise.all((await store.listKeys(journal.prefix,1)).map(async key=>(await store.readFresh(key)).value)));report.originalControlBudgetOperationsUnchanged=canonicalHash(before)===canonicalHash(await Promise.all(keys.map(async key=>canonicalHash((await store.readFresh(key)).value))));if(networkCalls||!report.nativeInvocationsUnchanged||!report.originalControlBudgetOperationsUnchanged){report.status='failed';report.errorCode='CONTENT_CONTEXT_SOURCE_CHANGED';process.exitCode=1}await persistProbeReport(path,report);console.log(JSON.stringify({status:report.status,errorCode:report.errorCode,selectedFrames:report.selectedFrames,completeFrozenFacts:report.completeFrozenFacts,networkCalls,nativeInvocationsUnchanged:report.nativeInvocationsUnchanged}))}
}
main().catch(error=>{console.error(error.message);process.exitCode=1});
