'use client';
import {useEffect,useRef,useState} from 'react';
import type {ProjectView} from '@/contracts/video/project';
import {SpecChip} from './SpecChip';
export type BriefSelection={durationSec?:number;aspect?:'16:9'|'9:16';styleSlug?:string;music?:NonNullable<ProjectView['quick']>['music']};
export function BriefCard({view,onDraft,onSelect,onMusic,disabled}:{view:ProjectView;onDraft:(text:string)=>void;onSelect:(text:string,patch:BriefSelection)=>void;onMusic:(music:NonNullable<ProjectView['quick']>['music'])=>void;disabled?:boolean}){
 const u=view.understanding,p=view.preferences,music=view.quick?.music,previous=useRef(u),[changed,setChanged]=useState<string[]>([]);
 useEffect(()=>{const fields=(['subject','audience','objective','summary','facts'] as const).filter(key=>JSON.stringify(previous.current[key])!==JSON.stringify(u[key]));previous.current=u;if(!fields.length)return;const start=setTimeout(()=>setChanged(fields),0),end=setTimeout(()=>setChanged([]),5000);return()=>{clearTimeout(start);clearTimeout(end)}},[u]);
 const line=(key:'subject'|'audience'|'objective',label:string,placeholder:string,prefill:string)=><div className={`brief-field ${changed.includes(key)?'just-updated':''}`}><dt>{label}</dt><dd>{u[key]||<button className="missing-field" onClick={()=>onDraft(prefill)}>{placeholder}</button>}{changed.includes(key)&&<small className="updated-label">已更新</small>}</dd></div>;
 return <><dl className="brief-fields">{line('subject','主题','还没说','我想做一个关于 ___ 的视频')}{line('audience','给谁看','给谁看？','这个视频主要给 ___ 看')}{line('objective','想达到什么','希望看完有什么感觉？','我希望大家看完以后 ___')}</dl>{u.summary.length>0&&<ul className="brief-points">{u.summary.slice(0,3).map((s,i)=><li key={i}>{s}</li>)}</ul>}{Boolean(u.facts?.length)&&<div className="brief-facts">{u.facts?.map((fact,i)=><span key={i} title={fact.source}>↳ {fact.text}<small>{fact.source==='uploaded_material'?'来自资料':'来自聊天'}</small></span>)}</div>}
 <div className="spec-chips"><SpecChip label={`${p.durationSec} 秒`} value={String(p.durationSec)} options={[20,25,30].map(n=>({value:String(n),label:`${n} 秒`}))} onSelect={value=>onSelect(`时长改成 ${value} 秒`,{durationSec:Number(value)})} disabled={disabled}/><SpecChip label={p.aspect==='9:16'?'竖屏':'横屏'} value={p.aspect} options={[{value:'9:16',label:'竖屏'},{value:'16:9',label:'横屏'}]} onSelect={value=>onSelect(`画面改成${value==='9:16'?'竖屏':'横屏'}`,{aspect:value as '9:16'|'16:9'})} disabled={disabled}/>{view.quick&&<SpecChip label={music?.mode==='off'?'不要配乐':music?.mode==='track'?'已选配乐':'自动配乐'} value={music?.mode==='track'?`track:${music.trackId}`:music?.mode||'auto'} options={[{value:'auto',label:'自动配乐'},{value:'off',label:'不要配乐'},...view.quick.tracks.map(t=>({value:`track:${t.id}`,label:t.title}))]} onSelect={value=>onMusic(value==='auto'?{mode:'auto'}:value==='off'?{mode:'off'}:{mode:'track',trackId:value.slice(6)})} disabled={disabled}/>}</div></>;
}
