'use client';
import {useEffect,useEffectEvent,useRef,useState} from 'react';
import type {ProjectView} from '@/contracts/video/project';
import type {useProject} from '@/hooks/video/use-project';
import {WelcomeCanvas} from '../welcome-canvas';
import {StyleInspiration} from './StyleInspiration';
import {StyleLibrary} from './StyleLibrary';
import {type StylePack} from '@/services/video/styles/registry';
import {CardShell} from './CardShell';
import {BriefCard,type BriefSelection} from './BriefCard';
import {StyleCard,canvasStyleRecommendations} from './StyleCard';
import {ScriptCard} from './ScriptCard';
import {ProgressRail} from './ProgressRail';
import {ResultCard} from './ResultCard';
import {deriveCanvasState,type CanvasTarget,type CanvasStage} from './state';
import {trackCanvasEvent} from '@/services/video/analytics/client';
export type CanvasRequest={target:CanvasTarget;shotId?:string;nonce:number;stage?:CanvasStage;focusBase?:CanvasTarget};
export function Canvas({project,onDraft,request,onShowCanvas}:{project:ReturnType<typeof useProject>;onDraft:(text:string)=>void;request?:CanvasRequest;onShowCanvas?:()=>void}){
 const [styleChanging,setStyleChanging]=useState(false);
 const [canvasView,setCanvasView]=useState<'flow'|'styles'>('flow'),[libraryFocusId,setLibraryFocusId]=useState<string>(),[pendingStyle,setPendingStyle]=useState<{style:StylePack;fromRecommend:boolean;surface:'card'|'library'}|null>(null),[toast,setToast]=useState<{id:string;name:string;previous:string|null;expectedBriefVersion?:number}|null>(null);
 const opener=useRef<HTMLElement|null>(null),openerIdentity=useRef({id:'',text:''}),savedScroll=useRef(0),libraryOpen=useRef(false),returnToStyle=useRef(false),closeWaiters=useRef<Array<()=>void>>([]),returnTarget=useRef<{target:CanvasTarget;shotId?:string}|null>(null);
 const view=project.view,state=deriveCanvasState(view),scroll=useRef<HTMLDivElement>(null),lastManual=useRef(0),[newContent,setNewContent]=useState(false),[selection,setSelection]=useState<{patch:BriefSelection;baseVersion:number;baseControlVersion:number;pending:boolean}|null>(null),[failure,setFailure]=useState('');
 const focus=request&&request.stage===state.stage&&request.focusBase===state.focus?request.target:state.focus,lastFocus=useRef(''),newTarget=useRef<CanvasTarget>(focus);
 function go(target:CanvasTarget,shotId?:string){if(target==='style-library')return;const node=document.getElementById(shotId?`canvas-shot-${shotId}`:`canvas-${target}`);if(node&&scroll.current?.contains(node))node.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});setNewContent(false)}
 useEffect(()=>{const key=`${state.stage}:${state.focus}`;if(lastFocus.current===key)return;lastFocus.current=key;newTarget.current=state.focus;const timer=setTimeout(()=>{if(Date.now()-lastManual.current<5000)setNewContent(true);else go(state.focus)},0);return()=>clearTimeout(timer)},[state.stage,state.focus]);
 const navigateRequest=useEffectEvent(()=>{if(!request)return;if(request.target==='style-library')openLibrary('chat');else if(libraryOpen.current){returnTarget.current={target:request.target,shotId:request.shotId};closeLibrary()}else go(request.target,request.shotId)});
 useEffect(()=>{if(!request)return;const timer=setTimeout(()=>navigateRequest(),30);return()=>clearTimeout(timer)},[request]);
 const analyticsProjectId=view?.projectId,briefVersion=view?.briefVersion,styleSlug=view?.preferences.styleSlug;
 useEffect(()=>{if(analyticsProjectId)trackCanvasEvent(analyticsProjectId,{name:'stage_enter',payload:{stage:state.stage}})},[analyticsProjectId,state.stage]);
 useEffect(()=>{
  if(!selection||selection.pending||!view||view.activeConversation||view.controlVersion<=selection.baseControlVersion)return;
  const patch=selection.patch,matches=(!patch.styleSlug||view.preferences.styleSlug===patch.styleSlug)&&(!patch.durationSec||view.preferences.durationSec===patch.durationSec)&&(!patch.aspect||view.preferences.aspect===patch.aspect);
  const timer=setTimeout(()=>{setSelection(null);if(!matches)setFailure('没改成功，原来的选择已保留，再试一次。')},0);return()=>clearTimeout(timer);
 },[selection,view]);
 // Keep the immediate selection until a newer authoritative brief arrives. Failed requests roll back immediately.
 const optimistic=selection&&view&&view.briefVersion===selection.baseVersion?selection.patch:null;
 const shown:ProjectView|null=view?{...view,preferences:{...view.preferences,...(optimistic?.durationSec?{durationSec:optimistic.durationSec}:{}),...(optimistic?.aspect?{aspect:optimistic.aspect}:{}),...(optimistic?.styleSlug?{styleSlug:optimistic.styleSlug}:{})},...(view.quick&&optimistic?.music?{quick:{...view.quick,music:optimistic.music}}:{})}:null;
 async function choose(text:string,patch:BriefSelection){if(!view)return;setFailure('');setSelection({patch,baseVersion:view.briefVersion,baseControlVersion:view.controlVersion,pending:true});const ok=patch.durationSec||patch.aspect?await project.setPreferences(patch):await project.sendText(text,'canvas');if(!ok){setSelection(null);setFailure('没改成功，原来的选择已保留，再试一次。')}else setSelection(old=>old?{...old,pending:false}:null)}
 async function music(next:NonNullable<ProjectView['quick']>['music']){if(!view)return;setSelection({patch:{music:next},baseVersion:view.briefVersion,baseControlVersion:view.controlVersion,pending:true});const ok=await project.setQuickMusic(next);setSelection(null);if(!ok)setFailure('没改成功，原来的配乐已保留，再试一次。')}
 const generate=()=>{if(view)trackCanvasEvent(view.projectId,{name:'generate_clicked',payload:{stage:state.stage}});void project.generateVideo()};
 const busy=project.sending||Boolean(selection?.pending),styleBusy=busy||project.generating||Boolean(view?.activeProduction)||Boolean(view?.activeConversation);
 const recommendations=canvasStyleRecommendations(shown);
 function restoreCanvas(){libraryOpen.current=false;setCanvasView('flow');setPendingStyle(null);requestAnimationFrame(()=>{requestAnimationFrame(()=>{if(scroll.current)scroll.current.scrollTop=savedScroll.current;if(returnTarget.current){const next=returnTarget.current;returnTarget.current=null;go(next.target,next.shotId);const node=document.getElementById(`canvas-${next.target}`);node?.setAttribute('tabindex','-1');node?.focus({preventScroll:true})}else if(returnToStyle.current){go('style');document.querySelector<HTMLElement>('#canvas-style button')?.focus({preventScroll:true})}else {const identity=openerIdentity.current,node=opener.current?.isConnected?opener.current:identity.id?document.getElementById(identity.id):Array.from(document.querySelectorAll<HTMLElement>('button')).find(button=>button.textContent===identity.text);node?.focus({preventScroll:true})}returnToStyle.current=false;for(const resolve of closeWaiters.current.splice(0))resolve()})})}
 function closeLibrary(selected=false){returnToStyle.current=selected;if(libraryOpen.current&&history.state?.view==='styles'){history.back()}else restoreCanvas()}
 function openLibrary(from:'welcome'|'card'|'chat'|'inspiration',focusId?:string){if(libraryOpen.current)return;opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;openerIdentity.current={id:opener.current?.id||'',text:opener.current?.textContent||''};savedScroll.current=scroll.current?.scrollTop||0;libraryOpen.current=true;setLibraryFocusId(focusId);setCanvasView('styles');setPendingStyle(null);history.pushState({...history.state,view:'styles',vbStyleLibrary:true,focusId},'');if(scroll.current)scroll.current.scrollTop=0;trackCanvasEvent(view?.projectId,{name:'style_library_open',payload:{from}})}
 const onHistory=useEffectEvent(()=>{if(history.state?.vbStyleLibrary){if(!libraryOpen.current){libraryOpen.current=true;setLibraryFocusId(history.state.focusId);setCanvasView('styles')}}else if(libraryOpen.current)restoreCanvas()}),onEscape=useEffectEvent((event:KeyboardEvent)=>{if(event.key==='Escape'&&libraryOpen.current){event.preventDefault();closeLibrary()}});
 useEffect(()=>{const pop=()=>onHistory(),key=(event:KeyboardEvent)=>onEscape(event);onHistory();window.addEventListener('popstate',pop);window.addEventListener('keydown',key);return()=>{window.removeEventListener('popstate',pop);window.removeEventListener('keydown',key)}},[]);
 useEffect(()=>{if(!pendingStyle)return;const timer=setTimeout(()=>document.querySelector<HTMLElement>('.style-confirm')?.scrollIntoView({block:'nearest',behavior:'instant'}),0);return()=>clearTimeout(timer)},[pendingStyle]);
 useEffect(()=>{if(!toast)return;const invalid=toast.expectedBriefVersion!==undefined&&briefVersion!==undefined&&(briefVersion>toast.expectedBriefVersion||briefVersion===toast.expectedBriefVersion&&styleSlug!==toast.id);const timer=setTimeout(()=>setToast(null),invalid?0:5000);return()=>clearTimeout(timer)},[toast,briefVersion,styleSlug]);
 async function applyStyle(style:StylePack,fromRecommend:boolean,surface:'card'|'library'){if(styleBusy)return;const previous=view?.preferences.styleSlug||null;setPendingStyle(null);setFailure('');setSelection(view?{patch:{styleSlug:style.id},baseVersion:view.briefVersion,baseControlVersion:view.controlVersion,pending:true}:null);if(!view&&libraryOpen.current)await new Promise<void>(resolve=>{closeWaiters.current.push(resolve);closeLibrary(true)});const ok=await project.setPreferences({styleSlug:style.id});if(!ok){setSelection(null);setFailure('没改成功，原来的选择已保留，再试一次。');return}setSelection(old=>old?{...old,pending:false}:null);trackCanvasEvent(project.preferencesReceipt.current?.projectId,{name:'style_selected',payload:{id:style.id,fromRecommend,origin:'canvas',rank:Math.max(0,recommendations.findIndex(item=>item.style.id===style.id)+1),surface}});setStyleChanging(false);setToast({id:style.id,name:style.nameZh,previous,expectedBriefVersion:project.preferencesReceipt.current?.briefVersion});onShowCanvas?.();if(libraryOpen.current)closeLibrary(true);else requestAnimationFrame(()=>go('style'))}
 function selectStyle(style:StylePack,fromRecommend:boolean,surface:'card'|'library'){if(styleBusy||style.id===shown?.preferences.styleSlug)return;if(view?.script||view?.currentResult)setPendingStyle({style,fromRecommend,surface});else void applyStyle(style,fromRecommend,surface)}
 async function undoStyle(){if(!toast||styleBusy||toast.expectedBriefVersion!==undefined&&view?.briefVersion!==toast.expectedBriefVersion)return;const old=toast;setToast(null);const ok=await project.setPreferences({styleSlug:old.previous},old.expectedBriefVersion);if(ok)trackCanvasEvent(view?.projectId,{name:'style_undo',payload:{id:old.id}});else setFailure('没改成功，原来的选择已保留，再试一次。');setSelection(null)}
 const confirm=pendingStyle?<div className="style-confirm" role="region" aria-label="确认更换画风"><p>已经写好脚本了，换成「{pendingStyle.style.nameZh}」会重画所有镜头。</p><div><button className="secondary-button" onClick={()=>{setPendingStyle(null);trackCanvasEvent(view?.projectId,{name:'style_change_confirm',payload:{result:'cancel'}})}}>先不换</button><button className="primary-button" disabled={styleBusy} onClick={()=>{trackCanvasEvent(view?.projectId,{name:'style_change_confirm',payload:{result:'confirm'}});void applyStyle(pendingStyle.style,pendingStyle.fromRecommend,pendingStyle.surface)}}>换成这个</button></div></div>:null;
 const feedback=<>{failure&&<p className="error-box">{failure}</p>}{toast&&<div className="style-toast" aria-live="polite"><span>已选「{toast.name}」</span><button className="text-button" disabled={styleBusy} onClick={()=>void undoStyle()}>撤销</button></div>}</>;
 if(canvasView==='styles')return <div className="work canvas-work style-library-work" ref={scroll}><StyleLibrary current={shown?.preferences.styleSlug} recommendations={recommendations.map(item=>item.style.id)} hint={shown?.understanding.subject} focusId={libraryFocusId} disabled={styleBusy} onClose={()=>closeLibrary()} onSelect={style=>selectStyle(style,recommendations.some(item=>item.style.id===style.id),'library')} projectId={view?.projectId}/>{confirm}{feedback}</div>;
 if(!shown||state.stage==='S0')return <div className="work canvas-work" ref={scroll}><WelcomeCanvas onExample={onDraft} extra={<StyleInspiration onOpen={id=>openLibrary(id?'inspiration':'welcome',id)}/>}/>{feedback}</div>;
 return <div className="work canvas-work" ref={scroll} aria-label="视频画布" onWheel={()=>lastManual.current=Date.now()} onTouchMove={()=>lastManual.current=Date.now()} onPointerDown={event=>{if(event.target===event.currentTarget)lastManual.current=Date.now()}} onKeyDown={event=>{if(['ArrowDown','ArrowUp','PageDown','PageUp','Home','End',' '].includes(event.key))lastManual.current=Date.now()}}><div className="work-inner canvas-inner">{'legacyMigrationNotice' in shown&&typeof shown.legacyMigrationNotice==='string'&&<p className="notice-inline">{shown.legacyMigrationNotice}</p>}{project.projectUpdate&&<p className="notice-inline">{project.projectUpdate}</p>}<ol className="flow-steps" aria-label="创作进度">{(['想法','画风','脚本','生成','成片'] as const).map((label,i)=><li className={i===({'S0':0,'S1':0,'S2':1,'S3':2,'S4':3,'S5':4,'S6':4}[state.stage])?'current':''} key={label}><span className="flow-index">{i+1}</span>{label}</li>)}</ol>
 <CardShell target="brief" number={1} title="想法" status={state.briefReady?'已完成':'进行中'} current={focus==='brief'} summary={shown.understanding.subject}><BriefCard view={shown} onDraft={onDraft} onSelect={(text,patch)=>void choose(text,patch)} onMusic={next=>void music(next)} disabled={busy}/></CardShell>
 <CardShell target="style" number={2} title="画风" status={shown.preferences.styleSlug?'已完成':state.briefReady?'需要你选':'待开始'} current={focus==='style'} summary={shown.preferences.styleSlug?`画风已选好，展开后可以换一个`:undefined}><StyleCard changing={styleChanging} onChange={setStyleChanging} view={shown} ready={state.briefReady} disabled={styleBusy} onOpen={()=>openLibrary('card')} onSelect={(style,fromRecommend)=>selectStyle(style,fromRecommend,'card')}/>{pendingStyle?.surface==='card'&&confirm}</CardShell>{feedback}
 <CardShell target="script" number={3} title="脚本" status={state.stale?'需要更新':shown.activeProduction||shown.script?.state==='drafting'?'进行中':shown.script?.state==='ready'?'已完成':'待开始'} current={focus==='script'} summary={shown.script?.summary}><ScriptCard view={shown} onDraft={onDraft} busy={project.generating} onGenerate={generate} onRetry={()=>void project.retryScript()} onRedo={id=>void project.updateQuick({redoShotId:id})}/></CardShell>{shown.activeProduction&&<ProgressRail activity={project.productionActivity} timingEstimates={shown.timingEstimates} shots={shown.script?.shots.length} onStop={()=>void project.stopProduction()}/>} {shown.productionFailure&&<div className="error-box"><p>{shown.productionFailure.message}</p><button className="text-button" disabled={project.generating} onClick={generate}>重试生成</button></div>}<CardShell target="result" number={5} title="成片" status={state.stale&&shown.currentResult?'需要更新':shown.currentResult?'已完成':shown.activeProduction?'进行中':'待开始'} current={focus==='result'} summary="视频已做好，可以随时播放和下载"><ResultCard view={shown} onGenerate={generate} onQuick={change=>void project.updateQuick(change)} onSelectFeedback={project.selectFeedback} restoration={project.restoration} busy={project.generating} stale={state.stale}/></CardShell>
 </div>{newContent&&<button className="canvas-new-content" onClick={()=>go(newTarget.current)}>有新内容 ↓</button>}</div>;
}
