'use client';
import type {ProjectView} from '@/contracts/video/project';
import type {useRestoreResult} from '@/hooks/video/use-restore-result';
import {VideoPlayer} from '../video-player';
import {ResultDownloads} from '../result-downloads';
import {ResultHistory} from '../result-history';
import {QuickPanel} from '../quick-panel';
import {listStyles} from '@/services/video/styles/registry';
export function ResultCard({view,onGenerate,onQuick,onSelectFeedback,restoration,busy,stale}:{view:ProjectView;onGenerate:()=>void;onQuick:(change:{music:NonNullable<ProjectView['quick']>['music']}|{redoShotId:string})=>void;onSelectFeedback:(artifactId:string,revisionId:string)=>void;restoration:ReturnType<typeof useRestoreResult>;busy:boolean;stale:boolean}){
 const result=view.currentResult,info=result?.quick;
 if(!result)return <p className="canvas-placeholder">视频做好后，会在这里播放和下载。你的想法和镜头都会保留。</p>;
 return <>{view.pendingInputs.length>0&&!view.activeProduction&&<p className="notice-inline">还有修改意见待补充，请告诉助手具体想改哪一处。</p>}<VideoPlayer key={result.artifactId} projectId={view.projectId} artifactId={result.artifactId} label="完整视频" portrait={(info?.aspect||view.preferences.aspect)==='9:16'} onSelect={()=>onSelectFeedback(result.artifactId,result.revisionId)}/><p className="media-note">{listStyles().find(s=>s.id===(info?.styleSlug||view.preferences.styleSlug))?.nameZh} · {info?.durationSec||view.preferences.durationSec} 秒 · {(info?.aspect||view.preferences.aspect)==='9:16'?'竖屏':'横屏'} · {info?.music?.title||'无配乐'} · 含 AI 生成标识</p><ResultDownloads key={`downloads:${result.artifactId}`} projectId={view.projectId} artifactId={result.artifactId} productionActive={Boolean(view.activeProduction)}/><ResultHistory key={`history:${result.artifactId}`} view={view} locked={['submitting','uncertain'].includes(restoration.state.phase)} onRestore={artifactId=>void restoration.restore(artifactId,view)} onSelectFeedback={onSelectFeedback}/>{restoration.state.message&&<p role={restoration.state.phase==='failed'?'alert':undefined} className="notice-inline">{restoration.state.message}</p>}{restoration.state.phase==='uncertain'&&<button className="text-button" onClick={()=>void restoration.reconnect()}>重新连接恢复</button>}{info&&<QuickPanel view={view} info={info} busy={busy} onChange={onQuick} musicOnly/>}{stale?<div className="canvas-generate"><p>新想法已经记下，脚本中标出了需要更新的内容。</p><button className="primary-action" disabled={busy||Boolean(view.activeProduction)||Boolean(view.pendingInputs.length)||!view.actions.some(a=>a.kind==='generate_video'&&a.enabled)} onClick={onGenerate}>按新想法重新生成</button></div>:<p className="postcard">满意就下载；想改哪里，直接告诉助手，比如“第 2 镜的月亮再大一点”。</p>}</>;
}
