'use client';
import type {ProjectView} from '@/contracts/video/project';
import {ShotTile} from './ShotTile';
export function ScriptCard({view,onDraft,onGenerate,onRetry,onRedo,busy}:{view:ProjectView;onDraft:(text:string)=>void;onGenerate:()=>void;onRetry:()=>void;onRedo:(id:string)=>void;busy:boolean}){
 const script=view.script,canGenerate=Boolean(view.understanding.subject.trim()&&view.preferences.styleSlug&&!view.pendingInputs.length&&view.actions.some(a=>a.kind==='generate_video'&&a.enabled)),stale=Boolean(script&&(script.state==='stale'||script.briefVersion<view.briefVersion));
 const pendingText=view.messages.filter(message=>view.pendingInputs.includes(message.id)).map(message=>message.text).join(' ');
 const pendingShot=(index:number)=>Boolean(view.activeProduction&&new RegExp(`第\\s*(?:${index+1}|${['一','二','三','四','五','六','七','八','九','十'][index]||index+1})\\s*镜`).test(pendingText));
 return <>{script?.summary&&<p>{script.summary}</p>}{script?.selectionReason&&<details className="script-reason"><summary>为什么这样讲</summary><p>{script.selectionReason}</p></details>}{script?.shots.length?<ol className={`canvas-shots ${stale?'is-stale':''}`}>{script.shots.map((shot,index)=><ShotTile key={shot.id} shot={shot} index={index} projectId={view.projectId} pending={pendingShot(index)} onDraft={onDraft} onRedo={view.currentResult?.quick?.shots.some(item=>item.id===shot.id)&&!stale?()=>onRedo(shot.id):undefined} disabled={busy||Boolean(view.activeProduction)}/>)}</ol>:<p className="canvas-placeholder">{view.preferences.styleSlug?'正在整理脚本，写好后会在这里逐镜呈现。':'选好画风后，这里会出现视频脚本。'}</p>}{!view.activeProduction&&!view.currentResult&&view.pendingInputs.length>0&&<p className="notice-inline">还有修改意见待补充，请告诉助手具体想改哪一处。</p>}{view.activeProduction&&view.pendingInputs.length>0&&<p className="welcome-note">收到的新想法会在下一版里改，已完成的镜头会保留。</p>}{script?.state==='drafting'&&<p className="welcome-note"><span className="spinner"/> 正在写脚本…</p>}{stale&&<p className="welcome-note">{view.activeProduction?'新想法会在下一版里改，当前制作继续保留。':'想法已更新，正在重新整理脚本。'}</p>}{script?.state==='failed'&&<div className="error-box"><p>{script.errorMessage||'脚本暂时没写好，已有想法已保留，可以重试。'}</p><button className="text-button" onClick={onRetry}>重试脚本</button></div>}{!view.activeProduction&&!view.currentResult&&view.preferences.styleSlug&&<div className="canvas-generate"><button className="primary-action" disabled={busy||!canGenerate} onClick={onGenerate}>{busy?'正在提交…':'生成视频 →'}</button><small>约 3–5 分钟，会依次画出每个镜头</small></div>}</>;
}
