'use client';
/* eslint-disable @next/next/no-img-element -- Private or optional sample URLs cannot be optimized publicly. */
import {useEffect,useState} from 'react';
import type {ProjectView} from '@/contracts/video/project';
import {PreviewPlayer} from '../preview-player';
type Shot=NonNullable<ProjectView['script']>['shots'][number];
const time=(n:number)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
export function ShotTile({shot,index,projectId,pending,onDraft,onRedo,disabled}:{shot:Shot;index:number;projectId:string;pending:boolean;onDraft:(text:string)=>void;onRedo?:()=>void;disabled?:boolean}){
 const [loadedPoster,setPoster]=useState<{artifactId:string;url:string}>(),[playingArtifact,setPlay]=useState('');
 useEffect(()=>{if(!shot.posterArtifactId)return;const abort=new AbortController();void fetch(`/api/video/projects/${projectId}/artifacts/${shot.posterArtifactId}/access?purpose=download`,{signal:abort.signal,cache:'no-store'}).then(async r=>{if(r.ok){const v=await r.json();if(typeof v.url==='string'&&!abort.signal.aborted)setPoster({artifactId:shot.posterArtifactId!,url:v.url})}}).catch(()=>{});return()=>abort.abort()},[projectId,shot.posterArtifactId]);
 const poster=loadedPoster?.artifactId===shot.posterArtifactId?loadedPoster?.url:undefined,play=Boolean(shot.clipArtifactId&&playingArtifact===shot.clipArtifactId);
 return <li id={`canvas-shot-${shot.id}`} className={`shot-tile is-${shot.state||'text'}`}><div className="shot-title"><strong>第 {index+1} 镜</strong><span>{time(shot.startSec)}–{time(shot.endSec)}</span>{pending&&<small className="badge">下一版会改</small>}</div>{play&&shot.clipArtifactId?<PreviewPlayer projectId={projectId} artifactId={shot.clipArtifactId} label={`第 ${index+1} 镜片段`}/>:shot.clipArtifactId?<button className="shot-poster" onClick={()=>setPlay(shot.clipArtifactId!)} aria-label={`播放第 ${index+1} 镜`}>{poster&&<img src={poster} onError={()=>setPoster(undefined)} alt={`第 ${index+1} 镜：${shot.visualIntent}`}/>}<span>▶ 播放这一镜</span></button>:poster?<img className="shot-preview" src={poster} onError={()=>setPoster(undefined)} alt={`第 ${index+1} 镜：${shot.visualIntent}`}/>:shot.state==='drawing'?<div className="shot-drawing"><span className="spinner"/>正在画…</div>:shot.state==='drawn'||shot.state==='rendered'?<p className="shot-ready">✓ 画面已画好{shot.state==='drawn'?'，正在准备播放':''}</p>:null}<p>{shot.scriptLine}</p><p className="shot-intent">{shot.visualIntent}</p><div className="shot-actions"><button className="text-button" onClick={()=>onDraft(`第 ${index+1} 镜改成：`)}>改这一镜</button>{onRedo&&<button className="text-button" disabled={disabled} onClick={onRedo}>重画这一镜</button>}</div></li>;
}
