'use client';
import {useEffect,useEffectEvent,useLayoutEffect,useRef,useState} from 'react';
import {listStyles,type StylePack} from '@/services/video/styles/registry';
import {recommendStyles,searchStyleFits} from '@/services/video/styles/recommendations';
import {trackCanvasEvent} from '@/services/video/analytics/client';
import {StyleSampleBudget} from '../style-picker';
import {StyleTile} from './StyleTile';
export function StyleLibrary({current,recommendations,hint='',focusId,disabled,onSelect,onClose,projectId}:{current?:string|null;recommendations:string[];hint?:string;focusId?:string;disabled?:boolean;onSelect:(style:StylePack)=>void;onClose:()=>void;projectId?:string}){
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('全部'),[scrolled,setScrolled]=useState(false),header=useRef<HTMLElement>(null);
 const categories=['全部','为你推荐',...new Set(listStyles().map(style=>style.categoryZh))],recommended=new Set([...recommendations,...recommendStyles(hint,6).map(style=>style.id)]),styles=searchStyleFits(search).filter(style=>category==='全部'||(category==='为你推荐'?recommended.has(style.id):style.categoryZh===category));
 const resultCount=styles.length;
 const searchChanged=useEffectEvent(()=>{setSearch(query);const work=header.current?.closest('.work');if(work&&query!==search)work.scrollTop=0;trackCanvasEvent(projectId,{name:'style_search',payload:{length:query.length,results:searchStyleFits(query).filter(style=>category==='全部'||(category==='为你推荐'?recommended.has(style.id):style.categoryZh===category)).length}})});
 useEffect(()=>{const timer=setTimeout(()=>searchChanged(),150);return()=>clearTimeout(timer)},[query,category]);
 useEffect(()=>{const node=header.current,work=node?.closest<HTMLElement>('.work');if(!work||!node)return;const update=()=>setScrolled(work.scrollTop>8);const resize=new ResizeObserver(()=>{work.style.scrollPaddingTop=`${node.offsetHeight+16}px`});resize.observe(node);work.addEventListener('scroll',update);return()=>{resize.disconnect();work.removeEventListener('scroll',update);work.style.scrollPaddingTop=''}},[]);
 useLayoutEffect(()=>{if(!focusId)return;const work=header.current?.closest<HTMLElement>('.work');if(work&&header.current)work.style.scrollPaddingTop=`${header.current.offsetHeight+16}px`;const tile=document.getElementById(`style-tile-${focusId}`);tile?.scrollIntoView({block:'start',behavior:'instant'});tile?.focus({preventScroll:true})},[focusId]);
 const groups=category==='全部'&&!search.trim()?[...new Set(styles.map(style=>style.categoryZh))]:[''];
 return <section className="style-library" aria-label="画风库"><header ref={header} className={`style-library-header ${scrolled?'scrolled':''}`}><div className="style-library-top"><button className="text-button" onClick={onClose}>← 返回画布</button><h1>画风库 <span>· {listStyles().length} 种</span></h1><label className="style-library-search"><span aria-hidden="true">⌕</span><input aria-label="搜索画风" placeholder="搜索用途或感觉，如：儿童、国风、科技" value={query} maxLength={200} onChange={event=>setQuery(event.target.value)}/></label></div><nav className="style-library-filters" aria-label="画风分类">{categories.map(name=><button key={name} aria-pressed={category===name} onClick={()=>{setCategory(name);const work=header.current?.closest('.work');if(work)work.scrollTop=0;trackCanvasEvent(projectId,{name:'style_filter',payload:{category:name}})}}>{name}</button>)}</nav><p className="style-result-count" aria-live="polite">找到 {resultCount} 种{disabled?' · 正在生成，稍后再换':''}</p></header><StyleSampleBudget key={`${search}:${category}`}><div className="style-library-content">{groups.map(group=>{const items=styles.filter(style=>!group||style.categoryZh===group);return <section key={group}>{group&&<h2>{group}<span>{items.length} 种</span></h2>}<div className="style-library-grid">{items.map(style=><StyleTile key={style.id} style={style} selected={current===style.id} recommended={recommendations.includes(style.id)} disabled={disabled} onSelect={()=>onSelect(style)}/>)}</div></section>})}{!styles.length&&<div className="style-empty"><h2>没找到「{search}」</h2><p>试试这些词，或者直接在右边告诉助手你想要的感觉。</p><div>{['儿童','国风','科技','复古'].map(word=><button className="secondary-button" key={word} onClick={()=>{setCategory('全部');setQuery(word)}}>{word}</button>)}</div></div>}</div></StyleSampleBudget></section>;
}
