import {lstat,mkdir} from 'node:fs/promises';
import {extname,isAbsolute,join} from 'node:path';
import {canonicalHash} from '@/services/video/domain/hash';
import type {Environment} from '@/services/video/config/environment';
import {dockerConfiguration} from '@/services/video/media/docker-executor';
import {runOwnedDocker} from '@/services/video/media/owned-docker';
import {technicalVideoQa} from '@/services/video/media/technical-qa';

/** Visible AI label and container metadata required for AI-generated media
 * (《人工智能生成合成内容标识办法》). The font ships in the media image (fonts-noto-cjk). */
export const aiLabel={text:'AI生成',metadata:'AIGC: generated by VideoBuddy',font:'/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc'} as const;
const safePath=(path:string)=>isAbsolute(path)&&/^\/[A-Za-z0-9_./-]+$/.test(path);

export interface QuickComposeInput{picturePath:string;music:{path:string;trackId:string}|null;width:number;height:number;fps:24|30|60;durationSec:number;title:string}
export function quickComposeKey(input:QuickComposeInput,runtimeDigest:string){return canonicalHash({version:'quick-compose-v1',picturePath:input.picturePath,music:input.music,width:input.width,height:input.height,fps:input.fps,durationSec:input.durationSec,runtimeDigest,label:aiLabel})}

/** ffmpeg: picture + (looped, faded, loudness-normalised music | silent stereo) + AI label. */
export function quickComposeArguments(image:string,user:string,key:string,input:QuickComposeInput,outputDir:string){
 if(!/^sha256:[a-f0-9]{64}$/.test(image)||!/^\d+:\d+$/.test(user)||!/^[a-f0-9]{64}$/.test(key)||!safePath(input.picturePath)||!safePath(outputDir)||input.music&&!safePath(input.music.path))throw Error('COMPOSITION_INVALID');
 if(!Number.isInteger(input.durationSec)||input.durationSec<5||input.durationSec>120||input.width%2||input.height%2)throw Error('COMPOSITION_INVALID');
 const d=input.durationSec,musicFile=input.music?`/input/music${extname(input.music.path).toLowerCase()}`:null;
 const args=['run','--rm','--name',`vb-quick-${key.slice(0,24)}`,'--network','none','--read-only','--cap-drop','ALL','--security-opt','no-new-privileges','--pids-limit','128','--cpus','4','--memory','2g','--memory-swap','2g','--user',user,'--tmpfs','/tmp:rw,nosuid,size=128m',
  '--mount',`type=bind,src=${input.picturePath},dst=/input/picture.mp4,readonly`,
  ...(input.music?['--mount',`type=bind,src=${input.music.path},dst=${musicFile},readonly`]:[]),
  '--mount',`type=bind,src=${outputDir},dst=/output`,image,
  'ffmpeg','-hide_banner','-loglevel','error','-xerror','-nostdin','-y','-threads','2','-filter_threads','2','-i','/input/picture.mp4'];
 if(musicFile)args.push('-stream_loop','-1','-i',musicFile);else args.push('-f','lavfi','-i','anullsrc=r=48000:cl=stereo');
 const label=`drawtext=fontfile=${aiLabel.font}:text=${aiLabel.text}:fontcolor=white@0.85:fontsize=h*0.026:box=1:boxcolor=black@0.32:boxborderw=10:x=w-tw-w*0.03:y=h*0.03`;
 args.push('-filter_complex',`[0:v]${label}[v]${musicFile?`;[1:a]atrim=0:${d},asetpts=N/SR/TB,afade=t=in:st=0:d=0.6,afade=t=out:st=${Math.max(0,d-2.5)}:d=2.5,loudnorm=I=-16:TP=-1.5:LRA=11,aresample=48000[a]`:''}`,
  '-map','[v]','-map',musicFile?'[a]':'1:a:0','-t',String(d),
  '-c:v','libx264','-preset','medium','-crf','20','-pix_fmt','yuv420p','-r',String(input.fps),'-color_primaries','bt709','-color_trc','bt709','-colorspace','bt709',
  '-c:a','aac','-b:a','160k','-ar','48000','-ac','2',
  '-metadata',`title=${input.title.replace(/[\r\n]/g,' ').slice(0,80)}`,'-metadata',`comment=${aiLabel.metadata}`,'-metadata',`aigc=${aiLabel.metadata}`,
  '-movflags','+faststart+use_metadata_tags','/output/final.mp4');
 return args;
}

export async function composeQuickFilm(root:string,input:QuickComposeInput,env:Environment=process.env,options:{assertActive?:()=>Promise<void>}={}){
 const config=dockerConfiguration(env,'quick-compose'),key=quickComposeKey(input,config.runtimeDigest);
 const stageDir=join(root,'quick-compose',key),outputDir=join(stageDir,'output'),outputPath=join(outputDir,'final.mp4');
 await mkdir(outputDir,{recursive:true,mode:0o700});
 const exists=await lstat(outputPath).then(info=>info.isFile()&&info.size>0,()=>false);
 if(!exists)await runOwnedDocker(quickComposeArguments(config.image,config.user,key,input,outputDir),config.timeoutSeconds*1000,config.image,options.assertActive);
 const qa=await technicalVideoQa(stageDir,config.image,'output/final.mp4',{width:input.width,height:input.height,durationSec:input.durationSec,fps:input.fps,audio:true,audioChannels:2});
 return{key,outputPath,qa};
}
