import {test,expect,type Page} from '@playwright/test';
import type {ProjectView,ArchivedMessage} from '../../../src/contracts/video/project';
const pid='10000000-0000-4000-8000-000000000001',op='20000000-0000-4000-8000-000000000002';
function message(role:'user'|'assistant',text:string,ui?:ArchivedMessage['ui']):ArchivedMessage{return{id:crypto.randomUUID(),ordinal:Date.now(),role,text,status:'completed',contentVersion:1,ui}}
function initial():ProjectView{return{projectId:pid,title:'中秋祝福',controlVersion:1,briefVersion:1,phase:'collecting',understanding:{subject:'中秋给家人的祝福',audience:'家人',objective:'',summary:['中秋想给家里人发个视频'],facts:[]},preferences:{durationSec:30,aspect:'16:9',language:'zh-CN',styleSlug:null,voiceMode:'none',musicMode:'composed',captions:'auto'},assets:[],messages:[message('user','中秋想给家里人发个视频'),message('assistant','好呀，中秋给家人的祝福。想要什么感觉的？',{quickReplies:[{label:'温暖团圆',text:'温暖团圆'},{label:'搞笑一点',text:'搞笑一点'}],canvasFocus:'brief'})],currentPreview:null,currentResult:null,previousResult:null,activeConversation:null,activeProduction:null,pendingInputs:[],actions:[{kind:'prepare_preview',enabled:true}],expiresAt:'2030-01-01T00:00:00Z',quick:{music:{mode:'auto'},tracks:[]}}}
async function fixture(page:Page){let view=initial(),paid=0;const sent:{text:string;origin?:string}[]=[];
 await page.route('**/api/video/session',r=>r.fulfill({json:{}}));
 await page.route(`**/api/video/projects/${pid}`,r=>r.fulfill({json:view}));
 await page.route('**/api/video/projects/*/analytics',r=>r.fulfill({json:{}}));
 await page.route('**/operations/*/events',r=>r.fulfill({contentType:'text/event-stream',body:': heartbeat\n\n'}));
 await page.route(`**/api/video/projects/${pid}/messages`,r=>{const body=r.request().postDataJSON();sent.push(body);view={...view,controlVersion:view.controlVersion+1,briefVersion:view.briefVersion+1,messages:[...view.messages,{...message('user',body.text),clientMessageId:body.clientMessageId,origin:body.origin}]};if(body.text==='温暖团圆'){view.messages.push(message('assistant','我在画布放了三个画风，点一个就行。',{canvasFocus:'style',recommendations:[{styleId:'paper-lantern',primary:true,reason:'温暖的夜景，灯光透过纸层'},{styleId:'papercut-red',primary:false,reason:'喜庆吉祥，适合节日问候'},{styleId:'ink-wash',primary:false,reason:'写意留白，适合诗意表达'}],canvasRefs:[{text:'三个画风',target:'style'}]}))}else if(body.text.includes('纸雕灯影')){view.preferences={...view.preferences,styleSlug:'paper-lantern'};view.script={briefVersion:view.briefVersion,state:'ready',summary:'月亮升起，一家人围坐，孩子提灯，定格祝福。',selectionReason:'从远景到团圆，让祝福更亲近。',shots:['月亮升起','一家人围坐','孩子提灯','定格祝福'].map((text,i)=>({id:`shot-${i+1}`,startSec:i*7.5,endSec:(i+1)*7.5,scriptLine:text,visualIntent:text,state:'text'}))};view.messages.push(message('assistant','脚本在画布，一共四镜，没问题就点生成视频。',{canvasFocus:'script',canvasRefs:[{text:'脚本',target:'script'}],quickReplies:[{label:'发视频号用',text:'发视频号用，竖屏'}]}))}return r.fulfill({status:202,json:{}})});
 await page.route(`**/api/video/projects/${pid}/preferences`,r=>{const body=r.request().postDataJSON();view={...view,controlVersion:view.controlVersion+1,briefVersion:view.briefVersion+1,preferences:{...view.preferences,...body.aspect&&{aspect:body.aspect},...body.durationSec&&{durationSec:body.durationSec}}};if(view.script)view.script={...view.script,briefVersion:view.briefVersion};return r.fulfill({json:view})});
 await page.route(`**/api/video/projects/${pid}/preview`,r=>{paid++;view={...view,controlVersion:view.controlVersion+1,activeProduction:{id:op,kind:'preview',status:'running',streamEpoch:0},phase:'preparing_preview'};return r.fulfill({status:202,json:{}})});
 await page.route('**/access?purpose=play',r=>r.fulfill({json:{url:'/fixture-video.mp4'}}));await page.route('**/fixture-video.mp4',r=>r.fulfill({status:404}));
 return {get view(){return view},set view(next:ProjectView){view=next},get paid(){return paid},sent};
}
for(const width of [1280,390])test(`gold journey accumulates idea, style, script and result at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});const f=await fixture(page);await page.goto(`/video/${pid}`);
 await page.getByRole('button',{name:'温暖团圆',exact:true}).click();expect(f.paid).toBe(0);
 if(width<960){await expect(page.locator('.canvas-update-bubble')).toContainText('画风');await page.getByRole('button',{name:/^画布/}).click()}
 await expect(page.locator('#canvas-style')).toHaveAttribute('data-status','需要你选');await expect(page.locator('#canvas-style .style-recommendations article')).toHaveCount(3);
 if(width>=960)await page.getByRole('textbox',{name:'说说想法，或发点资料'}).fill('正在写的草稿');
 await page.getByRole('button',{name:'用纸雕灯影',exact:true}).click();await expect(page.locator('.shot-tile')).toHaveCount(4);expect(f.sent.filter(m=>m.origin==='canvas')).toHaveLength(1);expect(f.paid).toBe(0);
 if(width>=960)await expect(page.getByRole('textbox',{name:'说说想法，或发点资料'})).toHaveValue('正在写的草稿');
 await page.reload();if(width<960)await page.getByRole('button',{name:/^画布/}).click();await expect(page.locator('.shot-tile')).toHaveCount(4);await page.screenshot({path:`.video-local/canvas-script-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'生成视频 →',exact:true}).click();await expect.poll(()=>f.paid).toBe(1);await expect(page.getByRole('region',{name:'生成进度'})).toBeVisible();
 f.view={...f.view,controlVersion:f.view.controlVersion+1,script:{...f.view.script!,shots:f.view.script!.shots.map((s,i)=>({...s,state:i===0?'drawing':'text'}))}};await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByText('正在画…',{exact:true})).toBeVisible();
 f.view={...f.view,controlVersion:f.view.controlVersion+1,activeProduction:null,phase:'ready',currentResult:{resultId:crypto.randomUUID(),revisionId:crypto.randomUUID(),artifactId:crypto.randomUUID(),bundleHash:'a'.repeat(64),createdAt:new Date().toISOString(),kind:'quick',quick:{styleSlug:'paper-lantern',aspect:'16:9',durationSec:30,music:null,shots:f.view.script!.shots.map(s=>({id:s.id,scriptLine:s.scriptLine,take:0}))}},script:{...f.view.script!,shots:f.view.script!.shots.map(s=>({...s,state:'rendered'}))}};await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'下载视频',exact:true})).toBeVisible();
 await expect(page.locator('#canvas-brief')).toBeAttached();await expect(page.locator('#canvas-style')).toBeAttached();await expect(page.locator('#canvas-script')).toBeAttached();await expect(page.locator('dialog')).toHaveCount(0);await expect(page.getByRole('status',{includeHidden:true})).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('stopping production is inline and needs a second click',async({page})=>{const f=await fixture(page);f.view={...f.view,activeProduction:{id:op,kind:'preview',status:'running',streamEpoch:0}};let stops=0;await page.route(`**/operations/${op}/cancel`,r=>{stops++;return r.fulfill({json:{}})});await page.goto(`/video/${pid}`);await page.getByRole('button',{name:'停止生成',exact:true}).click();expect(stops).toBe(0);await page.getByRole('button',{name:'确定停止？已画好的镜头会保留',exact:true}).click();await expect.poll(()=>stops).toBe(1);await expect(page.locator('dialog')).toHaveCount(0)});
test('new text-only script never reuses a previous draft poster with the same shot id',async({page})=>{
 const f=await fixture(page);f.view={...f.view,preferences:{...f.view.preferences,styleSlug:'paper-lantern'},messages:[...f.view.messages,message('assistant','脚本好了',{canvasFocus:'script'})],script:{briefVersion:1,state:'ready',summary:'旧脚本',selectionReason:'',shots:[{id:'shot-1',startSec:0,endSec:30,scriptLine:'旧镜头',visualIntent:'旧月亮',state:'drawn',posterArtifactId:'poster-old'}]}};
 await page.route('**/artifacts/poster-old/access?purpose=download',r=>r.fulfill({json:{url:'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=='}}));
 await page.goto(`/video/${pid}`);await expect(page.getByRole('img',{name:'第 1 镜：旧月亮'})).toBeVisible();
 f.view={...f.view,controlVersion:2,briefVersion:2,script:{...f.view.script!,briefVersion:2,shots:[{id:'shot-1',startSec:0,endSec:30,scriptLine:'新镜头',visualIntent:'新灯笼',state:'text'}]}};await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
 await expect(page.locator('#canvas-shot-shot-1')).toContainText('新灯笼');await expect(page.locator('#canvas-shot-shot-1 img')).toHaveCount(0);
});
test('manual navigation releases focus when production advances',async({page})=>{
 const f=await fixture(page);f.view={...f.view,preferences:{...f.view.preferences,styleSlug:'paper-lantern'},messages:[...f.view.messages,message('assistant','看想法',{canvasFocus:'script',canvasRefs:[{text:'想法',target:'brief'}]})],script:{briefVersion:1,state:'ready',summary:'团圆',selectionReason:'',shots:[]}};
 await page.goto(`/video/${pid}`);await page.getByRole('button',{name:'想法 ↗',exact:true}).click();await expect(page.locator('#canvas-brief')).toHaveAttribute('aria-current','step');
 f.view={...f.view,controlVersion:2,activeProduction:{id:op,kind:'preview',status:'running',streamEpoch:0}};await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.locator('#canvas-script')).toHaveAttribute('aria-current','step');await expect(page.locator('#canvas-brief')).not.toHaveAttribute('aria-current','step');
});

test.afterEach(async({page})=>{await expect(page.locator('dialog[open]')).toHaveCount(0)});
test('unresolved feedback stays visible and blocks regeneration after production',async({page})=>{
 const f=await fixture(page);f.view={...f.view,briefVersion:2,phase:'ready',pendingInputs:['needs-clarification'],currentResult:{resultId:crypto.randomUUID(),artifactId:crypto.randomUUID(),revisionId:crypto.randomUUID(),bundleHash:'a'.repeat(64),createdAt:new Date().toISOString(),briefVersion:1}};
 await page.goto(`/video/${pid}`);await expect(page.getByText('还有修改意见待补充，请告诉助手具体想改哪一处。',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'按新想法重新生成',exact:true})).toBeDisabled();expect(f.paid).toBe(0);
});
