import {test,expect,type Page} from '@playwright/test';
const pid='10000000-0000-4000-8000-000000000001';
async function fixture(page:Page,{welcome=false,script=false,busy=false,fail=false,fresh=false}={}){
 let writes=0,messages=0;
 let view={projectId:pid,title:'咖啡店介绍',controlVersion:1,briefVersion:1,phase:'collecting',understanding:{subject:welcome?'':'咖啡店介绍',audience:'客人',objective:'介绍',summary:[],facts:[]},preferences:{durationSec:30,aspect:'16:9',language:'zh-CN',styleSlug:script?'paper-lantern':null},assets:[],messages:welcome?[]:[{id:crypto.randomUUID(),ordinal:1,role:'assistant',text:'看全部画风',status:'completed',contentVersion:1,ui:{canvasRefs:[{text:'看全部画风',target:'style-library'}],canvasFocus:'style',recommendations:[{styleId:'urban-sketch',reason:'像走进街角咖啡店一样亲切',primary:true},{styleId:'watercolor',reason:'柔和水彩，让日常更温暖',primary:false},{styleId:'risograph',reason:'文创印刷感，适合独立小店',primary:false}]}}],currentResult:null,previousResult:null,activeConversation:null,activeProduction:busy?{id:'20000000-0000-4000-8000-000000000002',kind:'preview',status:'running',streamEpoch:0}:null,pendingInputs:[],actions:[],expiresAt:'2030-01-01T00:00:00Z',quick:{music:{mode:'auto'},tracks:[]},...(script?{script:{briefVersion:1,state:'ready',summary:'欢迎',selectionReason:'',shots:[]}}:{})};
 await page.route('**/api/video/**',route=>{const url=new URL(route.request().url());if(url.pathname==='/api/video/projects')return route.fulfill({json:{projectId:pid}});if(url.pathname.endsWith('/preferences')){writes++;if(fail)return route.fulfill({status:500,json:{error:{message:'失败'}}});const patch=route.request().postDataJSON().patch;view={...view,controlVersion:view.controlVersion+1,briefVersion:view.briefVersion+1,preferences:{...view.preferences,...patch}};return route.fulfill({json:view})}if(url.pathname.endsWith('/messages'))messages++;if(url.pathname===`/api/video/projects/${pid}`)return route.fulfill({json:view});return route.fulfill({json:{}})});
 await page.goto(fresh?'/video':`/video/${pid}`);
 if((await page.viewportSize())!.width<960)await page.getByRole('button',{name:/^画布/}).click();
 return {get writes(){return writes},get messages(){return messages},get view(){return view},set view(next:typeof view){view=next}};
}
const open=(page:Page)=>page.getByRole('button',{name:/浏览全部 43 种画风/}).click();
for(const [width,height] of [[1440,900],[1280,720],[1024,768],[390,844]])test(`one scroll owner, complete grid and opaque sticky header ${width}x${height}`,async({page})=>{
 await page.setViewportSize({width,height});await fixture(page);await page.waitForLoadState('networkidle');let covers=0;page.on('request',request=>{if(/style-samples\/.*\.jpg/.test(request.url()))covers++});const openingMs=await page.evaluate(()=>new Promise<number>(resolve=>{const button=Array.from(document.querySelectorAll('button')).find(node=>node.textContent?.includes('浏览全部 43'))!;const start=performance.now();button.click();requestAnimationFrame(()=>requestAnimationFrame(()=>resolve(performance.now()-start)))}));expect(openingMs).toBeLessThanOrEqual(300);await expect(page.locator('.style-library')).toBeVisible();await page.waitForTimeout(250);
 expect(covers).toBeLessThanOrEqual(12);
 const geometry=await page.locator('.work').evaluate(work=>({vertical:[work,...work.querySelectorAll('*')].filter(node=>node instanceof HTMLElement&&node.scrollHeight>node.clientHeight+1&&/auto|scroll/.test(getComputedStyle(node).overflowY)).map(node=>node.className),overflow:work.scrollWidth>work.clientWidth}));expect(geometry.vertical).toEqual(['work canvas-work style-library-work']);expect(geometry.overflow).toBe(false);await page.screenshot({path:`.video-local/style-library-${width}.png`});
 for(const fraction of [.25,.5,.75,1]){await page.locator('.work').evaluate((node,f)=>{node.dispatchEvent(new WheelEvent('wheel',{bubbles:true}));node.scrollTop=(node.scrollHeight-node.clientHeight)*f},fraction);await page.waitForTimeout(30);expect(await page.locator('.style-library-header').evaluate(header=>{const r=header.getBoundingClientRect();for(let x=r.left+20;x<r.right-20;x+=40){if(!header.contains(document.elementFromPoint(x,r.top+10)))return false}return true})).toBe(true)}
 await page.getByRole('textbox',{name:'搜索画风'}).fill('黑客');await expect(page.locator('.style-result-count')).toHaveText('找到 1 种');await expect(page.locator('.style-tile')).toHaveCount(1);
 await page.screenshot({path:`.video-local/style-search-${width}.png`});
});
test('welcome inspiration navigates and focuses without selecting or sending',async({page})=>{const f=await fixture(page,{welcome:true});await expect(page.locator('.style-inspiration .style-tile')).toHaveCount(6);await page.screenshot({path:'.video-local/style-welcome.png'});await page.locator('.style-inspiration .style-tile').first().click();await expect(page.locator('#style-tile-crayon-book')).toBeFocused();expect(f.writes).toBe(0);expect(f.messages).toBe(0);expect(await page.locator('#style-tile-crayon-book').evaluate(tile=>tile.getBoundingClientRect().top>=document.querySelector('.style-library-header')!.getBoundingClientRect().bottom)).toBe(true)});
for(const exit of ['button','escape','back'])test(`library ${exit} restores scroll and opener focus`,async({page})=>{await fixture(page);const trigger=page.getByRole('button',{name:/浏览全部 43/});await trigger.scrollIntoViewIfNeeded();const top=await page.locator('.work').evaluate(node=>node.scrollTop);await trigger.click();await page.locator('.work').evaluate(node=>{node.scrollTop=300});if(exit==='button')await page.getByRole('button',{name:'← 返回画布'}).click();else if(exit==='escape')await page.keyboard.press('Escape');else await page.goBack();await expect(page.locator('.style-library')).toHaveCount(0);await expect(trigger).toBeFocused();expect(await page.locator('.work').evaluate(node=>node.scrollTop)).toBeCloseTo(top,0)});
test('one-click recommendation, authoritative undo and five-second toast',async({page})=>{const f=await fixture(page);await page.screenshot({path:'.video-local/style-recommendations.png'});await page.locator('.style-recommendations .style-tile').first().click();await expect(page.locator('.style-selected')).toContainText('钢笔淡彩');await page.screenshot({path:'.video-local/style-selected.png'});await expect(page.locator('.style-toast')).toContainText('已选');await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(page.locator('.style-recommendations')).toBeVisible();expect(f.view.preferences.styleSlug).toBeNull();expect(f.writes).toBe(2);await page.locator('.style-recommendations .style-tile').first().click();await expect(page.locator('.style-toast')).toBeVisible();await expect(page.locator('.style-toast')).toHaveCount(0,{timeout:6500})});
test('existing script confirms inline; cancelling sends no request',async({page})=>{const f=await fixture(page,{script:true});await page.getByRole('button',{name:'换一个',exact:true}).click();await open(page);await page.getByRole('textbox',{name:'搜索画风'}).fill('watercolor');await expect(page.locator('.style-library .style-tile')).toHaveCount(1);await page.locator('.style-library .style-tile').click();await expect(page.getByRole('region',{name:'确认更换画风'})).toBeVisible();expect(f.writes).toBe(0);await page.getByRole('button',{name:'先不换'}).click();expect(f.writes).toBe(0);await page.locator('.style-library .style-tile').click();await page.getByRole('button',{name:'换成这个'}).click();await expect(page.locator('.style-library')).toHaveCount(0);expect(f.writes).toBe(1);expect(f.view.preferences.styleSlug).toBe('watercolor')});
test('busy styles disabled, no requests and readable explanation',async({page})=>{const f=await fixture(page,{busy:true});await open(page);await expect(page.locator('.style-tile').first()).toBeDisabled();await expect(page.locator('.style-result-count')).toContainText('正在生成，稍后再换');expect(f.writes).toBe(0)});
test('failed selection rolls back and preserves the library',async({page})=>{const f=await fixture(page,{fail:true});await open(page);await page.locator('.style-tile').first().click();await expect(page.locator('.error-box')).toContainText('没改成功');await expect(page.locator('.style-library')).toBeVisible();expect(f.view.preferences.styleSlug).toBeNull();await expect(page.locator('.style-toast')).toHaveCount(0)});
test('chat entry, keyboard search, empty suggestions and reduced motion',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await fixture(page);await page.getByRole('button',{name:'看全部画风 ↗'}).click();const search=page.getByRole('textbox',{name:'搜索画风'});await search.fill('没有这种风格');await expect(page.locator('.style-empty')).toBeVisible();await page.getByRole('button',{name:'国风',exact:true}).click();await expect(page.locator('.style-result-count')).toHaveText('找到 1 种');await page.locator('.style-tile').focus();await page.keyboard.press('Enter');await expect(page.locator('.style-library')).toHaveCount(0);await expect(page.locator('.style-selected')).toContainText('中国水墨');await expect(page.locator('.style-sample-video')).toHaveCount(0)});

test('history forward restores the library; ordinary chat navigation exits it',async({page})=>{await fixture(page);await open(page);await page.goBack();await expect(page.locator('.style-library')).toHaveCount(0);await page.goForward();await expect(page.locator('.style-library')).toBeVisible();await page.getByRole('button',{name:'在画布上看 ›'}).first().click();await expect(page.locator('.style-library')).toHaveCount(0);await expect(page.locator('#canvas-style')).toHaveAttribute('aria-current','step')});
test('return preserves change recommendations and original trigger focus',async({page})=>{await fixture(page,{script:true});await page.getByRole('button',{name:'换一个',exact:true}).click();await open(page);await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:/浏览全部 43/})).toBeFocused();await expect(page.locator('.style-recommendations')).toBeVisible()});
test('stale toast cannot undo a peer change to another style',async({page})=>{const f=await fixture(page);await page.locator('.style-recommendations .style-tile').first().click();await expect(page.locator('.style-toast')).toBeVisible();f.view={...f.view,briefVersion:3,controlVersion:3,preferences:{...f.view.preferences,styleSlug:'ink-wash'}};await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.locator('.style-selected')).toContainText('中国水墨');await expect(page.locator('.style-toast')).toHaveCount(0);expect(f.writes).toBe(1)});
test('fresh welcome choice saves directly and remains undoable without a director turn',async({page})=>{const events:string[]=[];page.on('request',request=>{if(request.url().endsWith('/api/video/analytics'))events.push(request.postDataJSON().event.name)});const f=await fixture(page,{fresh:true,welcome:true});await page.getByRole('button',{name:'逛逛全部画风 ↗'}).click();await page.getByRole('textbox',{name:'搜索画风'}).fill('ink-wash');await expect(page.locator('.style-library .style-tile')).toHaveCount(1);await page.locator('.style-tile').click();await expect(page.locator('.style-toast')).toBeVisible();await expect(page.getByRole('button',{name:'撤销',exact:true})).toBeEnabled();await page.getByRole('button',{name:'撤销',exact:true}).click();expect(f.view.preferences.styleSlug).toBeNull();expect(f.writes).toBe(2);expect(f.messages).toBe(0);await expect.poll(()=>events.filter(name=>name==='style_selected').length).toBe(1);expect(events).toContain('style_library_open');expect(events).toContain('style_search')});
