import {it,expect} from 'vitest';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {join} from 'node:path';import {tmpdir} from 'node:os';
import {FileStore} from '@/services/video/storage/file-store';
import {ProjectStore} from '@/services/video/storage/project-store';
import {LocalAssetBytes} from '@/services/video/assets/local-bytes';
import {reserveAsset,markUploaded} from '@/services/video/assets/reservations';
import {runSourceAnalysisOnce} from '@/services/video/assets/source-worker';
import {prepareImageAnalysis} from '@/services/video/assets/image-analysis-stage';
import type {ImageUnderstandingInput} from '@/contracts/video/image-understanding';
import type {ProjectControl} from '@/contracts/video/project';
import {updateJson} from '@/services/video/storage/atomic-store';
async function fixture(){const root=await mkdtemp(join(tmpdir(),'vb-image-analysis-')),store=new FileStore(root),projects=new ProjectStore(store),{projectId}=await projects.create('owner',{schemaVersion:5,clientCommandId:crypto.randomUUID(),clientCreateId:crypto.randomUUID()}),data=await readFile('docs/engineering/evidence/native-frame-3.png'),asset=await reserveAsset(store,`projects/${projectId}/control`,{filename:'图片.png',declaredMime:'image/png',declaredBytes:data.length,intendedUse:'参考画面',rightsConfirmed:true},crypto.randomUUID()),uploaded=await new LocalAssetBytes(root).put(projectId,asset.id,new Request('http://fixture/upload',{method:'PUT',body:data}),{declaredMime:'image/png',declaredBytes:data.length});await markUploaded(store,`projects/${projectId}/control`,asset.id,uploaded.sha256,uploaded.bytes);return{root,store,projects,projectId,asset,data}}
function output(input:ImageUnderstandingInput){return{schemaVersion:1,assetId:input.assetId,sourceSha256:input.sha256,mime:input.mime,description:'可见植物',observations:[],visibleText:[],uncertainties:['物种未确认'],scope:'provided_image_only',trust:'untrusted_material'}}
it('publishes actual bound image analysis once, changes brief, releases pending and cold-rechecks bytes',async()=>{
 const f=await fixture();let calls=0;const analyze=async(input:ImageUnderstandingInput,data:Uint8Array)=>{calls++;expect(Buffer.from(data).equals(f.data)).toBe(true);return output(input)};
 try{await runSourceAnalysisOnce(f.store,f.root,undefined,undefined,{analyze});expect((await f.store.readFresh<ProjectControl>(`projects/${f.projectId}/control`)).value.assets[0].status).toBe('ready');await prepareImageAnalysis(new ProjectStore(new FileStore(f.root)),f.root,f.projectId,f.asset.id,{analyze});const control=(await f.store.readFresh<ProjectControl>(`projects/${f.projectId}/control`)).value;expect(calls).toBe(1);expect(control).toMatchObject({briefVersion:1,inputPending:false});expect(control.assets[0]).toMatchObject({status:'ready'});const analysis=(await f.store.readFresh<{text:string;trust:string}>(control.assets[0].analysisRef!.key)).value;expect(analysis.text).toContain('可见植物');expect(analysis.trust).toBe('untrusted_material');await writeFile(new LocalAssetBytes(f.root).path(f.projectId,f.asset.id),Buffer.from('changed'));await expect(prepareImageAnalysis(f.projects,f.root,f.projectId,f.asset.id,{analyze})).rejects.toThrow();expect(calls).toBe(1)}finally{await rm(f.root,{recursive:true,force:true})}
});
it('retains unknown attempts and refuses duplicate model work after a restart',async()=>{const f=await fixture();let calls=0;const analyze=async()=>{calls++;throw Error('PROVIDER_TIMEOUT')};try{await expect(prepareImageAnalysis(f.projects,f.root,f.projectId,f.asset.id,{analyze})).rejects.toThrow('PROVIDER_TIMEOUT');await expect(prepareImageAnalysis(f.projects,f.root,f.projectId,f.asset.id,{analyze})).rejects.toThrow('EFFECT_UNKNOWN');expect(calls).toBe(1)}finally{await rm(f.root,{recursive:true,force:true})}});
it('rejects removal during analysis without publishing ready or changing brief',async()=>{const f=await fixture();try{await expect(prepareImageAnalysis(f.projects,f.root,f.projectId,f.asset.id,{analyze:async input=>{await updateJson(f.store,`projects/${f.projectId}/control`,(c:ProjectControl)=>({...c,assets:c.assets.map(a=>({...a,status:'removed'}))}));return output(input)}})).rejects.toThrow('IMAGE_ASSET_CHANGED');const c=(await f.store.readFresh<ProjectControl>(`projects/${f.projectId}/control`)).value;expect(c.briefVersion).toBe(0);expect(c.assets[0].analysisRef).toBeUndefined()}finally{await rm(f.root,{recursive:true,force:true})}});
it('records missing configuration without creating a model effect and resumes after configuration is provided',async()=>{const f=await fixture();try{await runSourceAnalysisOnce(f.store,f.root,undefined,undefined,{env:{VIDEO_GENERATION_ENABLED:'true'}});const c=(await f.store.readFresh<ProjectControl>(`projects/${f.projectId}/control`)).value;expect(c.assets[0]).toMatchObject({status:'uploaded',errorCode:'IMAGE_CONFIGURATION_REQUIRED'});expect(c.inputPending).toBe(true);expect(await f.store.listKeys(`projects/${f.projectId}/assets/${f.asset.id}/effects`,1)).toEqual([]);await runSourceAnalysisOnce(f.store,f.root,undefined,undefined,{analyze:async input=>output(input)});const ready=(await f.store.readFresh<ProjectControl>(`projects/${f.projectId}/control`)).value;expect(ready.assets[0].status).toBe('ready');expect(ready.assets[0].errorCode).toBeUndefined()}finally{await rm(f.root,{recursive:true,force:true})}});
it('denies new native model admission while generation is paused, before budget or effect writes',async()=>{const f=await fixture();const create=f.store.create.bind(f.store);f.store.create=async(key,value)=>{if(key.includes('/effects/'))throw Error('STOP_BEFORE_MODEL');await create(key,value)};try{await expect(prepareImageAnalysis(f.projects,f.root,f.projectId,f.asset.id,{env:{VIDEO_GENERATION_ENABLED:'false',MODEL_PROVIDER:'openai-compatible',MODEL_API_KEY:'local-test-only',MODEL_BASE_URL:'http://127.0.0.1:1/v1',VIDEO_VISUAL_MODEL:'test-model'},limits:{projectCalls:10,projectInputTokens:10000000,projectOutputTokens:100000,dailyCalls:10}})).rejects.toThrow('GENERATION_DISABLED');expect(await f.store.listKeys(`projects/${f.projectId}/budget-intents`,1)).toEqual([]);expect(await f.store.listKeys(`projects/${f.projectId}/assets/${f.asset.id}/effects`,1)).toEqual([])}finally{await rm(f.root,{recursive:true,force:true})}});
it('recovers a completed analysis after immutable archive acknowledgment is lost, without invoking the producer twice',async()=>{const f=await fixture();const create=f.store.create.bind(f.store);let fault=true,calls=0;f.store.create=async(key,value)=>{await create(key,value);if(fault&&key.includes('/analysis/')){fault=false;throw Error('EIO_ARCHIVE_ACK')}};const analyze=async(input:ImageUnderstandingInput)=>{calls++;return output(input)};try{await runSourceAnalysisOnce(f.store,f.root,undefined,undefined,{analyze});const interrupted=(await f.store.readFresh<ProjectControl>(`projects/${f.projectId}/control`)).value;expect(interrupted.assets[0].status).toBe('uploaded');await runSourceAnalysisOnce(new FileStore(f.root),f.root,undefined,undefined,{env:{VIDEO_GENERATION_ENABLED:'false'}});const recovered=(await f.store.readFresh<ProjectControl>(`projects/${f.projectId}/control`)).value;expect(recovered.assets[0].status).toBe('ready');expect(calls).toBe(1)}finally{await rm(f.root,{recursive:true,force:true})}});
