import {afterEach,expect,it} from 'vitest';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {runtimeLaunchOptions,sanitizedEnvironment} from '@/services/video/media/local/browser';
import {runProcess} from '@/services/video/media/local/ffmpeg';
import {renderArguments,assembleArguments} from '@/services/video/media/local/arguments';
import {computeStageKey} from '@/services/video/media/runtime';
const roots:string[]=[];
async function temporary(){const root=await mkdtemp(join(tmpdir(),'vb-local-runtime-'));roots.push(root);return root}
afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true})))});
it('requires Chromium sandbox except for an explicit development escape',()=>{
 expect(runtimeLaunchOptions({}).chromiumSandbox).toBe(true);
 expect(()=>runtimeLaunchOptions({NODE_ENV:'production',VIDEO_UNSAFE_NO_SANDBOX:'1'})).toThrow('SANDBOX_REQUIRED');
 expect(()=>runtimeLaunchOptions({NODE_ENV:'test',VIDEO_UNSAFE_NO_SANDBOX:'1'})).toThrow('SANDBOX_REQUIRED');
 expect(runtimeLaunchOptions({NODE_ENV:'development',VIDEO_UNSAFE_NO_SANDBOX:'1'}).chromiumSandbox).toBe(false);
});
it('launches browsers and media tools with no inherited secrets, proxies or Node injection',()=>{
 const env=sanitizedEnvironment({PATH:'/bin',HOME:'/secret-home',MODEL_API_KEY:'secret',HTTP_PROXY:'secret',NODE_OPTIONS:'--require evil',VIDEO_SESSION_SIGNING_KEY:'secret',LANG:'en_US.UTF-8'});
 expect(env).toEqual({NODE_ENV:'production',PATH:'/bin',LANG:'en_US.UTF-8',LC_ALL:'C.UTF-8'});
 expect(runtimeLaunchOptions({MODEL_API_KEY:'secret'}).env).not.toHaveProperty('MODEL_API_KEY');
});
it('keeps stage identities byte-compatible and fences changed sources',()=>{
 const job={projectId:'p',bundleHash:'b'.repeat(64),runtimeDigest:'c'.repeat(64),sourceHtml:'scene',logicalWidth:320,logicalHeight:180,outputWidth:320,outputHeight:180,fps:24 as const,startFrame:0,endFrame:24,seed:1,fence:0};
 expect(computeStageKey(job)).toBe('10fee6f3745f8c30aa5466fedc8cbe281598ccacdd01d12dc8c71a3c9aef55d1');expect(computeStageKey({...job,fence:1})).not.toBe(computeStageKey(job));
});
it('forces trusted encoder labeling and assembles with video stream copy',()=>{
 const args=renderArguments({logicalWidth:320,logicalHeight:180,outputWidth:320,outputHeight:180,fps:24,startFrame:0,endFrame:24},'/safe/font.ttf','/safe/clip.partial','jpeg');
 expect(args.join(' ')).toContain('drawtext=fontfile=/safe/font.ttf:text=AI生成');expect(args).toContain('image2pipe');
 const assembled=assembleArguments('/safe/list.txt','/safe/final.partial',{durationSec:1,title:'Test',musicPath:null});
 expect(assembled[assembled.indexOf('-c:v')+1]).toBe('copy');expect(assembled.join(' ')).not.toContain('drawtext');expect(assembled.join(' ')).toContain('AIGC: generated by VideoBuddy');
});
it('hard-stops timed-out processes and does not let them publish later',async()=>{
 const root=await temporary(),path=join(root,'late');
 await expect(runProcess(process.execPath,['-e',`setTimeout(()=>require('fs').writeFileSync(${JSON.stringify(path)},'bad'),500)`],{timeoutMs:30})).rejects.toThrow('MEDIA_PROCESS_TIMEOUT');
 await new Promise(resolve=>setTimeout(resolve,550));await expect(readFile(path)).rejects.toMatchObject({code:'ENOENT'});
});
it('feeds bounded stdin using backpressure and aborts immediately',async()=>{
 const root=await temporary(),path=join(root,'bytes');const chunks=Array.from({length:12},()=>Buffer.alloc(128*1024,7));
 await runProcess(process.execPath,['-e',`process.stdin.pipe(require('fs').createWriteStream(${JSON.stringify(path)}))`],{stdin:(async function*(){yield*chunks})(),timeoutMs:5000});
 expect((await readFile(path)).length).toBe(12*128*1024);
 const abort=new AbortController();abort.abort();await expect(runProcess(process.execPath,['-e','setInterval(()=>{},1000)'],{signal:abort.signal})).rejects.toThrow('MEDIA_ABORTED');
 await writeFile(join(root,'done'),'ok');
});
