import {it,expect,beforeEach,afterEach,vi} from 'vitest';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {FileStore} from '@/services/video/storage/file-store';
import {ProjectStore} from '@/services/video/storage/project-store';
import {issueSession,ownerHash} from '@/services/video/access/session';
import {writeWorkerHeartbeat} from '@/services/video/commands/worker-heartbeat';
import {POST,GET} from '@/app/api/video/projects/[projectId]/messages/route';
import {budgetKeys} from '@/services/video/config/environment';
import {runDirectorOperation} from '@/services/video/commands/local-director';
import {LocalEventLog} from '@/services/video/stream/local-event-log';
let root:string;
const origin='https://video.test',sid='1'.repeat(64),keys={current:'a'.repeat(64),keyId:'v1',environment:'test'};
beforeEach(async()=>{root=await mkdtemp(`${tmpdir()}/vb-message-target-`);for(const [k,v] of Object.entries({VIDEO_DATA_DIR:root,VIDEO_APP_ORIGIN:origin,VIDEO_SESSION_SIGNING_KEY:keys.current,VIDEO_SESSION_KEY_ID:keys.keyId,VIDEO_ENVIRONMENT:keys.environment,VIDEO_GENERATION_ENABLED:'true',MODEL_API_KEY:'local-unit-only',VIDEO_DIRECTOR_MODEL:'local-unit'}))vi.stubEnv(k,v);for(const k of budgetKeys)vi.stubEnv(k,'100000');await writeWorkerHeartbeat(root)});
afterEach(async()=>{vi.unstubAllEnvs();await rm(root,{recursive:true,force:true})});
it('archives the exact user feedback target and cold replay cannot silently retarget the same message',async()=>{
 const projects=new ProjectStore(new FileStore(root));const {projectId}=await projects.create(ownerHash(sid,keys),{schemaVersion:5,clientCommandId:crypto.randomUUID(),clientCreateId:crypto.randomUUID()});
 const target={artifactId:crypto.randomUUID(),revisionId:crypto.randomUUID(),sourceTimeMs:null},input={schemaVersion:5,clientCommandId:crypto.randomUUID(),clientMessageId:crypto.randomUUID(),text:'音乐调小一点',attachmentIds:[],target,origin:'canvas'},context={params:Promise.resolve({projectId})};
 const request=(value:unknown=input,session=sid)=>new Request(`${origin}/api/video/projects/${projectId}/messages`,{method:'POST',headers:{origin,'Content-Type':'application/json',cookie:`vb-session=${issueSession(keys,Date.now(),session).token}`},body:JSON.stringify(value)});
 expect((await POST(request(input,'2'.repeat(64)),context)).status).toBe(404);
 expect((await POST(request(),context)).status).toBe(202);
 const cold=new ProjectStore(new FileStore(root)),control=await cold.access(ownerHash(sid,keys),projectId);
 expect((await cold.messages(control))[0]).toMatchObject({target,role:'user',text:input.text,origin:'canvas'});
 expect((await POST(request(),context)).status).toBe(202);
 expect((await POST(request({...input,target:{...target,artifactId:crypto.randomUUID()}}),context)).status).toBe(409);
 expect((await POST(request({...input,origin:undefined}),context)).status).toBe(409);
 const response=await GET(new Request(`${origin}/api/video/projects/${projectId}/messages`,{headers:{cookie:`vb-session=${issueSession(keys,Date.now(),sid).token}`}}),context);
 expect(response.status).toBe(200);expect((await response.json()).messages[0]).toMatchObject({target,origin:'canvas'});
 expect((await cold.messages(await cold.access(ownerHash(sid,keys),projectId)))).toHaveLength(1);
 let calls=0;
 await runDirectorOperation(cold.store,new LocalEventLog(root),projectId,control.activeConversation!,{decide:async(_understanding,messages)=>{calls++;expect(messages[0].target).toEqual(target);return{action:'acknowledge',reply:'已收到你的修改反馈。',effect:'no_change',executionIntent:'none',evidenceMessageIds:[(await cold.messages(control))[0].id]}}});
 expect(calls).toBe(1);
 const fresh=await cold.access(ownerHash(sid,keys),projectId);expect((await cold.messages(fresh))[0].target).toEqual(target);expect(fresh.activeProduction).toBeFalsy();
});
it.each(['null','omitted'])('keeps %s targets without inferring an artifact or an old playback position',async mode=>{
 const projects=new ProjectStore(new FileStore(root)),{projectId}=await projects.create(ownerHash(sid,keys),{schemaVersion:5,clientCommandId:crypto.randomUUID(),clientCreateId:crypto.randomUUID()});
 const input={schemaVersion:5,clientCommandId:crypto.randomUUID(),clientMessageId:crypto.randomUUID(),text:'先不改',attachmentIds:[],...(mode==='null'?{target:null}:{})};
 const request=new Request(`${origin}/api/video/projects/${projectId}/messages`,{method:'POST',headers:{origin,'Content-Type':'application/json',cookie:`vb-session=${issueSession(keys,Date.now(),sid).token}`},body:JSON.stringify(input)});
 expect((await POST(request,{params:Promise.resolve({projectId})})).status).toBe(202);
 const [message]=await projects.messages(await projects.access(ownerHash(sid,keys),projectId));
 expect(message.target).toBe(mode==='null'?null:undefined);
});
