import {afterEach,describe,expect,it,vi} from 'vitest';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {FileStore} from '@/services/video/storage/file-store';
import {ProjectStore} from '@/services/video/storage/project-store';
import {saveShotProgress,publishShotArtifact} from '@/services/video/quick/shot-media';
import {resolveArtifact} from '@/services/video/exports/access';
import {StreamEventSchema} from '@/contracts/video/commands';
const roots:string[]=[];afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true})))});
async function setup(){const root=await mkdtemp(join(tmpdir(),'vb-shots-'));roots.push(root);const store=new FileStore(root),projects=new ProjectStore(store);const{projectId}=await projects.create('owner',{schemaVersion:5,clientCommandId:randomUUID(),clientCreateId:randomUUID()});const base=`projects/${projectId}/quick/b0/${'a'.repeat(16)}`;return{root,store,projects,projectId,base}}
describe('private shot media',()=>{
 it('persists real clip bytes, fences publication, and authorizes only its owner',async()=>{const s=await setup(),path=join(s.root,'clip.mp4'),bytes=Buffer.alloc(2048,42);await writeFile(path,bytes);const input={projectId:s.projectId,operationId:randomUUID(),revisionId:randomUUID(),base:s.base,shotId:'shot-1',take:0,path,mime:'video/mp4' as const,expectedSha256:createHash('sha256').update(bytes).digest('hex')};const active=vi.fn(async()=>{});const id=await publishShotArtifact(s.projects,s.root,input,active);expect(active).toHaveBeenCalledTimes(2);expect((await resolveArtifact(s.projects,'owner',s.projectId,id)).objectRef.sha256).toBe(input.expectedSha256);await expect(resolveArtifact(s.projects,'stranger',s.projectId,id)).rejects.toThrow('ACCESS_NOT_FOUND');expect(await publishShotArtifact(s.projects,s.root,{...input,operationId:randomUUID(),revisionId:randomUUID()},active)).toBe(id);await expect(publishShotArtifact(s.projects,s.root,{...input,expectedSha256:'0'.repeat(64)},active)).rejects.toThrow('QA_FAILED');await expect(publishShotArtifact(s.projects,s.root,input,async()=>{throw Error('PREVIEW_STALE')})).rejects.toThrow('PREVIEW_STALE');await saveShotProgress(s.projects,s.base,'shot-1',{state:'drawing',take:1});await expect(resolveArtifact(s.projects,'owner',s.projectId,id)).rejects.toThrow('ACCESS_NOT_FOUND')});
 it('rejects non-PNG posters and preserves the poster when its clip finishes',async()=>{const s=await setup(),path=join(s.root,'poster.png'),base={projectId:s.projectId,operationId:randomUUID(),revisionId:randomUUID(),base:s.base,shotId:'shot-1',take:0,path,mime:'image/png' as const};await writeFile(path,'not an image');await expect(publishShotArtifact(s.projects,s.root,base,async()=>{})).rejects.toThrow('OUTPUT_INVALID');await saveShotProgress(s.projects,s.base,'shot-1',{state:'drawn',take:0,posterArtifactId:'poster-id'});await saveShotProgress(s.projects,s.base,'shot-1',{state:'rendered',take:0,clipArtifactId:'clip-id'});const value=(await s.store.readFresh<{shots:Record<string,unknown>}>(`${s.base}/canvas`)).value;expect(value.shots['shot-1']).toEqual({state:'rendered',take:0,posterArtifactId:'poster-id',clipArtifactId:'clip-id'})});
 it('accepts compact script/shot events and quantitative progress',()=>{const base={schemaVersion:5,projectId:randomUUID(),operationId:randomUUID(),epoch:0,eventId:randomUUID(),createdAt:new Date().toISOString()};expect(StreamEventSchema.parse({...base,type:'script.ready',payload:{briefVersion:2}}).type).toBe('script.ready');expect(StreamEventSchema.parse({...base,type:'shot.updated',payload:{shotId:'shot-1',state:'drawn',index:0,total:4}}).type).toBe('shot.updated');expect(StreamEventSchema.parse({...base,type:'activity.updated',payload:{stage:'visual',label:'已完成 2/4 镜',completed:2,total:4,unit:'shots'}}).type).toBe('activity.updated')});
});
