export const encoderPolicy={codec:'libx264',preset:'faster',crf:20,pixelFormat:'yuv420p',color:'bt709',jpegQuality:92,version:'local-video-v1'} as const;
export const aiMetadata='AIGC: generated by VideoBuddy';
export function renderArguments(job:{outputWidth:number;outputHeight:number;fps:number;startFrame:number;endFrame:number;logicalWidth?:number;logicalHeight?:number},fontPath:string,output:string,format:'jpeg'|'png'){
 if(!/^\/[A-Za-z0-9_./-]+$/.test(fontPath))throw Error('FONT_PATH_INVALID');
 const label=`drawtext=fontfile=${fontPath}:text=AI生成:fontcolor=white@0.85:fontsize='max(12,h*0.026)':box=1:boxcolor=black@0.32:boxborderw=10:x=w-tw-w*0.03:y=h*0.03`;
 return['-hide_banner','-loglevel','error','-xerror','-y','-threads','2','-filter_threads','2','-f','image2pipe','-c:v',format==='jpeg'?'mjpeg':'png','-framerate',String(job.fps),'-i','pipe:0','-an','-vf',`scale=${job.outputWidth}:${job.outputHeight}:flags=lanczos,${label}`,'-c:v',encoderPolicy.codec,'-threads','2','-preset',encoderPolicy.preset,'-crf',String(encoderPolicy.crf),'-g',String(job.fps*2),'-pix_fmt',encoderPolicy.pixelFormat,'-color_primaries','bt709','-color_trc','bt709','-colorspace','bt709','-movflags','+faststart','-frames:v',String(job.endFrame-job.startFrame),'-f','mp4',output];
}
export function assembleArguments(listPath:string,output:string,input:{durationSec:number;title:string;musicPath:string|null}){
 const args=['-hide_banner','-loglevel','error','-xerror','-nostdin','-y','-threads','2','-filter_threads','2','-filter_complex_threads','2','-f','concat','-safe','0','-protocol_whitelist','file,pipe','-i',listPath];
 if(input.musicPath)args.push('-stream_loop','-1','-protocol_whitelist','file,pipe','-i',input.musicPath);else args.push('-f','lavfi','-i','anullsrc=r=48000:cl=stereo');
 if(input.musicPath)args.push('-filter_complex',`[1:a]atrim=0:${input.durationSec},asetpts=N/SR/TB,afade=t=in:st=0:d=0.6,afade=t=out:st=${Math.max(0,input.durationSec-2.5)}:d=2.5,loudnorm=I=-16:TP=-1.5:LRA=11,aresample=48000[a]`);
 args.push('-map','0:v:0','-map',input.musicPath?'[a]':'1:a:0','-c:v','copy','-c:a','aac','-b:a','192k','-ar','48000','-ac','2','-t',String(input.durationSec),'-metadata',`title=${input.title.replace(/[\r\n\0]/g,' ').slice(0,80)}`,'-metadata',`comment=${aiMetadata}`,'-metadata',`aigc=${aiMetadata}`,'-movflags','+faststart+use_metadata_tags','-f','mp4',output);return args;
}
