'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {recentProjectIds} from '@/hooks/video/recent-projects';
import {Icon} from './icons';
interface Recent{projectId:string;title:string;phase:string;expiresAt:string}
const phaseLabels:Record<string,string>={collecting:'正在聊想法',generating:'正在生成',ready:'视频已完成',attention:'需要处理',cancelled:'已停止'};
function useRecent(open:boolean){const [projects,setProjects]=useState<Recent[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);useEffect(()=>{if(!open)return;const abort=new AbortController();async function load(){setLoading(true);setError('');try{const ids=recentProjectIds();if(!ids.length){setProjects([]);return}const response=await fetch('/api/video/projects/lookup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({schemaVersion:5,projectIds:ids}),signal:abort.signal});const value=await response.json();if(!response.ok)throw Error(value.error?.message||'暂时无法读取项目。');setProjects(value.projects)}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'暂时无法读取项目。')}finally{if(!abort.signal.aborted)setLoading(false)}}void load();return()=>abort.abort()},[open]);return{projects,error,loading}}
function ProjectList({projects,onSelect}:{projects:Recent[];onSelect?:()=>void}){return <ul className="project-list">{projects.map(project=><li key={project.projectId}><Link className="project-row" href={`/video/${project.projectId}`} onClick={onSelect}><span className="project-icon" aria-hidden="true"><Icon name="play"/></span><span className="project-copy"><strong>{project.title}</strong><small>{phaseLabels[project.phase]||'已保存'} · 保存至 {new Date(project.expiresAt).toLocaleDateString('zh-CN')}</small></span><Icon name="chev"/></Link></li>)}</ul>}
export function RecentProjectsMenu(){const [open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),{projects,error,loading}=useRecent(open);useEffect(()=>{if(!open)return;function outside(e:PointerEvent){if(!root.current?.contains(e.target as Node))setOpen(false)}function key(e:KeyboardEvent){if(e.key==='Escape'){setOpen(false);trigger.current?.focus()}}document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key)}},[open]);return <div className="recent-menu" ref={root}><button ref={trigger} className="text-button" aria-expanded={open} aria-controls="recent-project-menu" onClick={()=>setOpen(!open)}>我的视频</button>{open&&<section id="recent-project-menu" className="recent-menu-panel" aria-label="我的视频"><h2>我的视频</h2>{loading?<p>正在读取…</p>:error?<p>{error}</p>:projects.length?<ProjectList projects={projects.slice(0,8)} onSelect={()=>setOpen(false)}/>:<p>这个浏览器还没有可访问的视频项目。</p>}<Link className="text-button" href="/video/projects">查看全部 ›</Link></section>}</div>}
export function RecentProjectsPage(){const{projects,error,loading}=useRecent(true);return <main className="vb-easy"><header className="topbar"><Link className="brand" href="/video">VideoBuddy</Link><Link href="/video" className="text-button">新建视频</Link></header><div className="work-inner"><h1>我的视频</h1>{loading?<p>正在读取…</p>:error?<p>{error}</p>:projects.length?<ProjectList projects={projects}/>:<p>这个浏览器还没有可访问的视频项目。</p>}<Link href="/video/metrics" className="text-button">使用情况</Link><p className="welcome-note">这里只记录本浏览器最近打开的项目。清除浏览器数据后无法自动找回。</p></div></main>}
